//
//  FeaturedDeckContent.swift
//  TranslateHelper
//
//  Static card content for all featured decks (f1–f12).
//

import Foundation

struct FeaturedDeckContent {

    // swiftlint:disable function_body_length
    static func cards(forId id: String) -> [DeckCard] {
        switch id {

        // MARK: - f1 Mexico City Slang (50 cards)
        case "f1":
            return [
                DeckCard(english: "cool/awesome", spanish: "chido/a", targetLang: "es"),
                DeckCard(english: "beer", spanish: "chela", targetLang: "es"),
                DeckCard(english: "buddy/friend", spanish: "cuate", targetLang: "es"),
                DeckCard(english: "dude (very common)", spanish: "güey", targetLang: "es"),
                DeckCard(english: "wow/oh man", spanish: "híjole", targetLang: "es"),
                DeckCard(english: "come on/alright", spanish: "ándale", targetLang: "es"),
                DeckCard(english: "right on/let's go", spanish: "órale", targetLang: "es"),
                DeckCard(english: "cheap/bad quality", spanish: "chafa", targetLang: "es"),
                DeckCard(english: "money (slang)", spanish: "feria", targetLang: "es"),
                DeckCard(english: "money", spanish: "lana", targetLang: "es"),
                DeckCard(english: "work/job", spanish: "jale", targetLang: "es"),
                DeckCard(english: "truth/for real", spanish: "neta", targetLang: "es"),
                DeckCard(english: "hell yeah", spanish: "a huevo", targetLang: "es"),
                DeckCard(english: "no way/come on", spanish: "no manches", targetLang: "es"),
                DeckCard(english: "good vibes", spanish: "buena onda", targetLang: "es"),
                DeckCard(english: "bad vibes", spanish: "mala onda", targetLang: "es"),
                DeckCard(english: "amazed/shocked", spanish: "curado", targetLang: "es"),
                DeckCard(english: "I like them (they're cool)", spanish: "me cae", targetLang: "es"),
                DeckCard(english: "I don't like them", spanish: "no me cae", targetLang: "es"),
                DeckCard(english: "it's tough/intense", spanish: "está cañón", targetLang: "es"),
                DeckCard(english: "I don't care", spanish: "me vale", targetLang: "es"),
                DeckCard(english: "right now (or maybe later — very ambiguous!)", spanish: "ahorita", targetLang: "es"),
                DeckCard(english: "honestly/for real", spanish: "al chile", targetLang: "es"),
                DeckCard(english: "problem/issue", spanish: "pedo", targetLang: "es"),
                DeckCard(english: "to be drunk", spanish: "estar pedo", targetLang: "es"),
                DeckCard(english: "what's up/what's the deal", spanish: "qué pedo", targetLang: "es"),
                DeckCard(english: "to play along with someone", spanish: "dar el avión", targetLang: "es"),
                DeckCard(english: "close friend/bro", spanish: "carnal", targetLang: "es"),
                DeckCard(english: "problem/bind", spanish: "clavo", targetLang: "es"),
                DeckCard(english: "fast/urgently", spanish: "en chinga", targetLang: "es"),
                DeckCard(english: "badass/awesome", spanish: "chingón", targetLang: "es"),
                DeckCard(english: "awesome/skilled", spanish: "fregón", targetLang: "es"),
                DeckCard(english: "bad/ugly/mean", spanish: "gacho", targetLang: "es"),
                DeckCard(english: "to leave/take off", spanish: "jalarse", targetLang: "es"),
                DeckCard(english: "no way/absolutely not", spanish: "ni madres", targetLang: "es"),
                DeckCard(english: "what's up?", spanish: "qué onda", targetLang: "es"),
                DeckCard(english: "it cracked me up", spanish: "me raía", targetLang: "es"),
                DeckCard(english: "yes (slang)", spanish: "simon", targetLang: "es"),
                DeckCard(english: "no (slang)", spanish: "nel", targetLang: "es"),
                DeckCard(english: "later/goodbye", spanish: "pa' luego", targetLang: "es"),
                DeckCard(english: "to drink alcohol", spanish: "pistear", targetLang: "es"),
                DeckCard(english: "hungover", spanish: "crudo", targetLang: "es"),
                DeckCard(english: "damn (intensifier)", spanish: "pinche", targetLang: "es"),
                DeckCard(english: "shady deal/person", spanish: "transa", targetLang: "es"),
                DeckCard(english: "kid/brat", spanish: "escuincle", targetLang: "es"),
                DeckCard(english: "morbid curiosity/drama", spanish: "morbo", targetLang: "es"),
                DeckCard(english: "to give someone a lift", spanish: "dar un ride", targetLang: "es"),
                DeckCard(english: "person from CDMX", spanish: "chilango", targetLang: "es"),
                DeckCard(english: "work/job (synonym for jale)", spanish: "chamba", targetLang: "es"),
                DeckCard(english: "to be at 100%/feeling great", spanish: "estar al cien", targetLang: "es"),
            ]

        // MARK: - f2 Romantic Phrases (40 cards)
        case "f2":
            return [
                DeckCard(english: "I like you/love you (warm but not deep)", spanish: "te quiero", targetLang: "es"),
                DeckCard(english: "I love you (deep love)", spanish: "te amo", targetLang: "es"),
                DeckCard(english: "I like you romantically", spanish: "me gustas", targetLang: "es"),
                DeckCard(english: "you're very handsome/beautiful", spanish: "eres muy guapo/a", targetLang: "es"),
                DeckCard(english: "do you have a boyfriend/girlfriend?", spanish: "¿tienes novio/a?", targetLang: "es"),
                DeckCard(english: "do you want to go out with me?", spanish: "¿quieres salir conmigo?", targetLang: "es"),
                DeckCard(english: "you drive me crazy", spanish: "me vuelves loco/a", targetLang: "es"),
                DeckCard(english: "you're my other half", spanish: "eres mi media naranja", targetLang: "es"),
                DeckCard(english: "I miss you", spanish: "te extraño", targetLang: "es"),
                DeckCard(english: "I think about you", spanish: "pienso en ti", targetLang: "es"),
                DeckCard(english: "you make me very happy", spanish: "me haces muy feliz", targetLang: "es"),
                DeckCard(english: "can I have your number?", spanish: "¿me das tu número?", targetLang: "es"),
                DeckCard(english: "you're incredible", spanish: "eres increíble", targetLang: "es"),
                DeckCard(english: "I'm crazy about you", spanish: "me encantas", targetLang: "es"),
                DeckCard(english: "you have beautiful eyes", spanish: "tienes ojos hermosos", targetLang: "es"),
                DeckCard(english: "do you want to be my boyfriend/girlfriend?", spanish: "¿quieres ser mi novio/a?", targetLang: "es"),
                DeckCard(english: "I'm in love with you", spanish: "estoy enamorado/a de ti", targetLang: "es"),
                DeckCard(english: "I can't live without you", spanish: "no puedo vivir sin ti", targetLang: "es"),
                DeckCard(english: "you're the best thing that's happened to me", spanish: "eres lo mejor que me ha pasado", targetLang: "es"),
                DeckCard(english: "when can I see you again?", spanish: "¿cuándo te puedo ver de nuevo?", targetLang: "es"),
                DeckCard(english: "you have me on cloud nine", spanish: "me tienes en las nubes", targetLang: "es"),
                DeckCard(english: "you're my favourite person", spanish: "eres mi persona favorita", targetLang: "es"),
                DeckCard(english: "my heart (endearment)", spanish: "mi corazón", targetLang: "es"),
                DeckCard(english: "my love", spanish: "amor mío", targetLang: "es"),
                DeckCard(english: "darling/honey", spanish: "cariño", targetLang: "es"),
                DeckCard(english: "sweetheart (lit: sky)", spanish: "cielo", targetLang: "es"),
                DeckCard(english: "baby (endearment)", spanish: "bebé", targetLang: "es"),
                DeckCard(english: "give me a hug", spanish: "dame un abrazo", targetLang: "es"),
                DeckCard(english: "can I have a kiss?", spanish: "¿me das un beso?", targetLang: "es"),
                DeckCard(english: "I'm nervous", spanish: "estoy nervioso/a", targetLang: "es"),
                DeckCard(english: "you make me nervous", spanish: "me pones nervioso/a", targetLang: "es"),
                DeckCard(english: "I want to know you better", spanish: "quiero conocerte mejor", targetLang: "es"),
                DeckCard(english: "you're special to me", spanish: "eres especial para mí", targetLang: "es"),
                DeckCard(english: "I'd like to invite you to dinner", spanish: "me gustaría invitarte a cenar", targetLang: "es"),
                DeckCard(english: "I have butterflies in my stomach", spanish: "tengo mariposas en el estómago", targetLang: "es"),
                DeckCard(english: "I really liked meeting you", spanish: "me gustó mucho conocerte", targetLang: "es"),
                DeckCard(english: "where have you been all my life?", spanish: "¿dónde has estado toda mi vida?", targetLang: "es"),
                DeckCard(english: "I'll always be here for you", spanish: "siempre estaré aquí para ti", targetLang: "es"),
                DeckCard(english: "you're perfectly imperfect", spanish: "eres perfectamente imperfecto/a", targetLang: "es"),
                DeckCard(english: "you and me against the world", spanish: "tú y yo contra el mundo", targetLang: "es"),
            ]

        // MARK: - f3 Medical Spanish (60 cards)
        case "f3":
            return [
                DeckCard(english: "it hurts", spanish: "me duele", targetLang: "es"),
                DeckCard(english: "I have a headache", spanish: "me duele la cabeza", targetLang: "es"),
                DeckCard(english: "my stomach hurts", spanish: "me duele el estómago", targetLang: "es"),
                DeckCard(english: "I have a fever", spanish: "tengo fiebre", targetLang: "es"),
                DeckCard(english: "I have a cough", spanish: "tengo tos", targetLang: "es"),
                DeckCard(english: "my throat hurts", spanish: "me duele la garganta", targetLang: "es"),
                DeckCard(english: "I feel nauseous", spanish: "tengo náuseas", targetLang: "es"),
                DeckCard(english: "I vomited", spanish: "vomité", targetLang: "es"),
                DeckCard(english: "I have diarrhea", spanish: "tengo diarrea", targetLang: "es"),
                DeckCard(english: "I'm dizzy", spanish: "estoy mareado/a", targetLang: "es"),
                DeckCard(english: "I cut myself", spanish: "me corté", targetLang: "es"),
                DeckCard(english: "I fell", spanish: "me caí", targetLang: "es"),
                DeckCard(english: "I twisted my ankle", spanish: "me torcí el tobillo", targetLang: "es"),
                DeckCard(english: "I'm allergic to...", spanish: "soy alérgico/a a...", targetLang: "es"),
                DeckCard(english: "I take medication for...", spanish: "tomo medicamentos para...", targetLang: "es"),
                DeckCard(english: "I'm diabetic", spanish: "soy diabético/a", targetLang: "es"),
                DeckCard(english: "I have high blood pressure", spanish: "tengo presión alta", targetLang: "es"),
                DeckCard(english: "I need a doctor", spanish: "necesito un médico", targetLang: "es"),
                DeckCard(english: "call an ambulance", spanish: "llame a una ambulancia", targetLang: "es"),
                DeckCard(english: "where is the pharmacy?", spanish: "¿dónde está la farmacia?", targetLang: "es"),
                DeckCard(english: "I need this prescription", spanish: "necesito esta receta", targetLang: "es"),
                DeckCard(english: "do you have something for pain?", spanish: "¿tiene algo para el dolor?", targetLang: "es"),
                DeckCard(english: "pills/tablets", spanish: "pastillas", targetLang: "es"),
                DeckCard(english: "medicine syrup", spanish: "jarabe", targetLang: "es"),
                DeckCard(english: "the doctor's consultation", spanish: "la consulta", targetLang: "es"),
                DeckCard(english: "the doctor", spanish: "el médico", targetLang: "es"),
                DeckCard(english: "the hospital", spanish: "el hospital", targetLang: "es"),
                DeckCard(english: "the emergency room", spanish: "la sala de emergencias", targetLang: "es"),
                DeckCard(english: "the clinic", spanish: "la clínica", targetLang: "es"),
                DeckCard(english: "insurance", spanish: "el seguro", targetLang: "es"),
                DeckCard(english: "the prescription", spanish: "la receta", targetLang: "es"),
                DeckCard(english: "the blood test", spanish: "el análisis de sangre", targetLang: "es"),
                DeckCard(english: "blood pressure", spanish: "la presión arterial", targetLang: "es"),
                DeckCard(english: "the heart", spanish: "el corazón", targetLang: "es"),
                DeckCard(english: "the lung", spanish: "el pulmón", targetLang: "es"),
                DeckCard(english: "the liver", spanish: "el hígado", targetLang: "es"),
                DeckCard(english: "the knee", spanish: "la rodilla", targetLang: "es"),
                DeckCard(english: "the ankle", spanish: "el tobillo", targetLang: "es"),
                DeckCard(english: "the back", spanish: "la espalda", targetLang: "es"),
                DeckCard(english: "the chest", spanish: "el pecho", targetLang: "es"),
                DeckCard(english: "the wrist", spanish: "la muñeca", targetLang: "es"),
                DeckCard(english: "the hip", spanish: "la cadera", targetLang: "es"),
                DeckCard(english: "the head", spanish: "la cabeza", targetLang: "es"),
                DeckCard(english: "the throat", spanish: "la garganta", targetLang: "es"),
                DeckCard(english: "the arm", spanish: "el brazo", targetLang: "es"),
                DeckCard(english: "the leg", spanish: "la pierna", targetLang: "es"),
                DeckCard(english: "I feel very sick", spanish: "me siento muy mal", targetLang: "es"),
                DeckCard(english: "I have chills", spanish: "tengo escalofríos", targetLang: "es"),
                DeckCard(english: "I can't breathe well", spanish: "no puedo respirar bien", targetLang: "es"),
                DeckCard(english: "do you have English-speaking doctors?", spanish: "¿tiene médicos que hablen inglés?", targetLang: "es"),
                DeckCard(english: "the deductible/copay", spanish: "el deducible", targetLang: "es"),
                DeckCard(english: "antibiotics", spanish: "antibióticos", targetLang: "es"),
                DeckCard(english: "paracetamol/acetaminophen", spanish: "paracetamol", targetLang: "es"),
                DeckCard(english: "ibuprofen", spanish: "ibuprofeno", targetLang: "es"),
                DeckCard(english: "cream/ointment", spanish: "crema", targetLang: "es"),
                DeckCard(english: "I need water", spanish: "necesito agua", targetLang: "es"),
                DeckCard(english: "I have chest pain", spanish: "tengo dolor de pecho", targetLang: "es"),
                DeckCard(english: "it hurts when I breathe", spanish: "me duele al respirar", targetLang: "es"),
                DeckCard(english: "I lost consciousness", spanish: "perdí el conocimiento", targetLang: "es"),
                DeckCard(english: "I have an infection", spanish: "tengo una infección", targetLang: "es"),
            ]

        // MARK: - f4 Food & Markets (40 cards)
        case "f4":
            return [
                DeckCard(english: "the bill please", spanish: "la cuenta por favor", targetLang: "es"),
                DeckCard(english: "what do you recommend?", spanish: "¿qué recomienda?", targetLang: "es"),
                DeckCard(english: "without spice please", spanish: "sin picante por favor", targetLang: "es"),
                DeckCard(english: "very spicy", spanish: "muy picante", targetLang: "es"),
                DeckCard(english: "is the tip included?", spanish: "¿está incluido el servicio?", targetLang: "es"),
                DeckCard(english: "to go", spanish: "para llevar", targetLang: "es"),
                DeckCard(english: "to eat here", spanish: "para comer aquí", targetLang: "es"),
                DeckCard(english: "do you have vegetarian options?", spanish: "¿tiene opciones vegetarianas?", targetLang: "es"),
                DeckCard(english: "I'm vegetarian", spanish: "soy vegetariano/a", targetLang: "es"),
                DeckCard(english: "gluten-free", spanish: "sin gluten", targetLang: "es"),
                DeckCard(english: "tacos", spanish: "tacos", targetLang: "es"),
                DeckCard(english: "quesadillas", spanish: "quesadillas", targetLang: "es"),
                DeckCard(english: "tamales", spanish: "tamales", targetLang: "es"),
                DeckCard(english: "hearty hominy soup", spanish: "pozole", targetLang: "es"),
                DeckCard(english: "fried tortillas in salsa with egg", spanish: "chilaquiles", targetLang: "es"),
                DeckCard(english: "corn tortilla", spanish: "la tortilla de maíz", targetLang: "es"),
                DeckCard(english: "sauce/salsa", spanish: "la salsa", targetLang: "es"),
                DeckCard(english: "chili pepper", spanish: "el chile", targetLang: "es"),
                DeckCard(english: "lime (in Mexico limón = lime)", spanish: "el limón", targetLang: "es"),
                DeckCard(english: "sour cream", spanish: "la crema", targetLang: "es"),
                DeckCard(english: "cheese", spanish: "el queso", targetLang: "es"),
                DeckCard(english: "avocado", spanish: "el aguacate", targetLang: "es"),
                DeckCard(english: "beans", spanish: "los frijoles", targetLang: "es"),
                DeckCard(english: "rice", spanish: "el arroz", targetLang: "es"),
                DeckCard(english: "the market", spanish: "el mercado", targetLang: "es"),
                DeckCard(english: "how much is it?", spanish: "¿cuánto cuesta?", targetLang: "es"),
                DeckCard(english: "can I have a kilo of...?", spanish: "¿me da un kilo de...?", targetLang: "es"),
                DeckCard(english: "it's very expensive", spanish: "está muy caro", targetLang: "es"),
                DeckCard(english: "do you have change?", spanish: "¿tiene cambio?", targetLang: "es"),
                DeckCard(english: "the market stall", spanish: "el puesto", targetLang: "es"),
                DeckCard(english: "corn on the cob", spanish: "elote", targetLang: "es"),
                DeckCard(english: "corn in a cup with mayo cheese and chili", spanish: "esquites", targetLang: "es"),
                DeckCard(english: "slow-cooked spiced meat stew", spanish: "la birria", targetLang: "es"),
                DeckCard(english: "ceviche-style marinated shrimp", spanish: "el aguachile", targetLang: "es"),
                DeckCard(english: "beer with lime juice and spices", spanish: "el michelada", targetLang: "es"),
                DeckCard(english: "basket taco (steamed, sold on street)", spanish: "el taco de canasta", targetLang: "es"),
                DeckCard(english: "scrambled eggs", spanish: "huevos revueltos", targetLang: "es"),
                DeckCard(english: "sweet bread (Mexican pastry)", spanish: "el pan dulce", targetLang: "es"),
                DeckCard(english: "traditional Mexican pot coffee", spanish: "el café de olla", targetLang: "es"),
                DeckCard(english: "warm corn-based drink", spanish: "atole", targetLang: "es"),
            ]

        // MARK: - f5 Flirting & Banter (34 cards)
        case "f5":
            return [
                DeckCard(english: "you're very hot", spanish: "estás muy bueno/a", targetLang: "es"),
                DeckCard(english: "you have great vibes", spanish: "tienes muy buena vibra", targetLang: "es"),
                DeckCard(english: "are you from here?", spanish: "¿eres de aquí?", targetLang: "es"),
                DeckCard(english: "where are you from?", spanish: "¿de dónde eres?", targetLang: "es"),
                DeckCard(english: "I really like you (personality)", spanish: "me caes muy bien", targetLang: "es"),
                DeckCard(english: "you're very funny", spanish: "eres muy chistoso/a", targetLang: "es"),
                DeckCard(english: "you make me laugh", spanish: "me haces reír", targetLang: "es"),
                DeckCard(english: "what are you doing right now?", spanish: "¿qué estás haciendo ahorita?", targetLang: "es"),
                DeckCard(english: "do you want to get a drink?", spanish: "¿quieres tomar algo?", targetLang: "es"),
                DeckCard(english: "you're very interesting", spanish: "eres muy interesante", targetLang: "es"),
                DeckCard(english: "you caught my attention", spanish: "me llama la atención", targetLang: "es"),
                DeckCard(english: "you have great style", spanish: "tienes mucho estilo", targetLang: "es"),
                DeckCard(english: "do you dance?", spanish: "¿bailas?", targetLang: "es"),
                DeckCard(english: "will you teach me to dance?", spanish: "¿me enseñas a bailar?", targetLang: "es"),
                DeckCard(english: "what are you doing this weekend?", spanish: "¿qué haces el fin de semana?", targetLang: "es"),
                DeckCard(english: "we have to hang out", spanish: "tenemos que salir", targetLang: "es"),
                DeckCard(english: "I liked you from the moment I saw you", spanish: "me gustas desde que te vi", targetLang: "es"),
                DeckCard(english: "you're always on my mind", spanish: "siempre estás en mi mente", targetLang: "es"),
                DeckCard(english: "don't be shy", spanish: "no seas tímido/a", targetLang: "es"),
                DeckCard(english: "tell me about yourself", spanish: "platícame de ti", targetLang: "es"),
                DeckCard(english: "you have an incredible smile", spanish: "tienes una sonrisa increíble", targetLang: "es"),
                DeckCard(english: "I love your eyes", spanish: "me encantan tus ojos", targetLang: "es"),
                DeckCard(english: "are you single?", spanish: "¿eres soltero/a?", targetLang: "es"),
                DeckCard(english: "I won't bite (playful)", spanish: "no te voy a morder", targetLang: "es"),
                DeckCard(english: "you're a delight/charmer", spanish: "eres un encanto", targetLang: "es"),
                DeckCard(english: "will you give me a chance?", spanish: "¿me das chance?", targetLang: "es"),
                DeckCard(english: "we have chemistry", spanish: "tenemos química", targetLang: "es"),
                DeckCard(english: "I won't forget you tonight", spanish: "esta noche no te olvido", targetLang: "es"),
                DeckCard(english: "you look really good", spanish: "te ves muy bien", targetLang: "es"),
                DeckCard(english: "you're my type", spanish: "eres mi tipo", targetLang: "es"),
                DeckCard(english: "what do you do for work?", spanish: "¿a qué te dedicas?", targetLang: "es"),
                DeckCard(english: "I like you a lot", spanish: "me gustas mucho", targetLang: "es"),
                DeckCard(english: "will you join me?", spanish: "¿me acompañas?", targetLang: "es"),
                DeckCard(english: "you look so handsome/beautiful today", spanish: "qué guapo/a estás hoy", targetLang: "es"),
            ]

        // MARK: - f6 Sports & Fútbol (36 cards)
        case "f6":
            return [
                DeckCard(english: "the match/game", spanish: "el partido", targetLang: "es"),
                DeckCard(english: "the goal", spanish: "el gol", targetLang: "es"),
                DeckCard(english: "the goalkeeper", spanish: "el portero", targetLang: "es"),
                DeckCard(english: "the forward/striker", spanish: "el delantero", targetLang: "es"),
                DeckCard(english: "the midfielder", spanish: "el mediocampista", targetLang: "es"),
                DeckCard(english: "the defender", spanish: "el defensa", targetLang: "es"),
                DeckCard(english: "the referee", spanish: "el árbitro", targetLang: "es"),
                DeckCard(english: "the red card", spanish: "la tarjeta roja", targetLang: "es"),
                DeckCard(english: "the yellow card", spanish: "la tarjeta amarilla", targetLang: "es"),
                DeckCard(english: "the penalty kick", spanish: "el penal", targetLang: "es"),
                DeckCard(english: "the corner kick", spanish: "el tiro de esquina", targetLang: "es"),
                DeckCard(english: "offside", spanish: "el fuera de lugar", targetLang: "es"),
                DeckCard(english: "the field/pitch", spanish: "la cancha", targetLang: "es"),
                DeckCard(english: "the stands", spanish: "la tribuna", targetLang: "es"),
                DeckCard(english: "the stadium", spanish: "el estadio", targetLang: "es"),
                DeckCard(english: "the coach/manager", spanish: "el entrenador", targetLang: "es"),
                DeckCard(english: "he/she scored a goal", spanish: "metió un gol", targetLang: "es"),
                DeckCard(english: "amazing goal!", spanish: "¡golazo!", targetLang: "es"),
                DeckCard(english: "it's tied", spanish: "está empatado", targetLang: "es"),
                DeckCard(english: "we're winning", spanish: "vamos ganando", targetLang: "es"),
                DeckCard(english: "we're losing", spanish: "vamos perdiendo", targetLang: "es"),
                DeckCard(english: "the score", spanish: "el marcador", targetLang: "es"),
                DeckCard(english: "extra time", spanish: "el tiempo extra", targetLang: "es"),
                DeckCard(english: "penalty shootout", spanish: "los penales", targetLang: "es"),
                DeckCard(english: "the fan", spanish: "el aficionado", targetLang: "es"),
                DeckCard(english: "the national team", spanish: "la selección", targetLang: "es"),
                DeckCard(english: "Club América (CDMX team)", spanish: "el América", targetLang: "es"),
                DeckCard(english: "Guadalajara/Chivas", spanish: "las Chivas", targetLang: "es"),
                DeckCard(english: "Mexico national team", spanish: "el Tri", targetLang: "es"),
                DeckCard(english: "come on Mexico!", spanish: "¡arriba México!", targetLang: "es"),
                DeckCard(english: "what's the score?", spanish: "¿cómo va el marcador?", targetLang: "es"),
                DeckCard(english: "he/she is playing very well", spanish: "está jugando muy bien", targetLang: "es"),
                DeckCard(english: "the league", spanish: "la liga", targetLang: "es"),
                DeckCard(english: "the championship", spanish: "el campeonato", targetLang: "es"),
                DeckCard(english: "Mexico Cup", spanish: "la Copa MX", targetLang: "es"),
                DeckCard(english: "the derby/classic rivalry match", spanish: "el clásico", targetLang: "es"),
            ]

        // MARK: - f7 Argentine Slang (30 cards)
        case "f7":
            return [
                DeckCard(english: "dude/idiot (friendly)", spanish: "boludo", targetLang: "es"),
                DeckCard(english: "hey/mate", spanish: "che", targetLang: "es"),
                DeckCard(english: "cool/awesome", spanish: "copado", targetLang: "es"),
                DeckCard(english: "work/job", spanish: "laburo", targetLang: "es"),
                DeckCard(english: "to eat", spanish: "morfar", targetLang: "es"),
                DeckCard(english: "kid/guy", spanish: "pibe", targetLang: "es"),
                DeckCard(english: "girl/woman", spanish: "mina", targetLang: "es"),
                DeckCard(english: "mess/chaos", spanish: "quilombo", targetLang: "es"),
                DeckCard(english: "very (intensifier)", spanish: "re", targetLang: "es"),
                DeckCard(english: "beer", spanish: "birra", targetLang: "es"),
                DeckCard(english: "laziness", spanish: "fiaca", targetLang: "es"),
                DeckCard(english: "sweet talk/flirting", spanish: "chamullo", targetLang: "es"),
                DeckCard(english: "to pay", spanish: "garpar", targetLang: "es"),
                DeckCard(english: "police", spanish: "cana", targetLang: "es"),
                DeckCard(english: "to steal", spanish: "afanar", targetLang: "es"),
                DeckCard(english: "dude/guy", spanish: "chabón", targetLang: "es"),
                DeckCard(english: "for real/truth", spanish: "posta", targetLang: "es"),
                DeckCard(english: "fake/counterfeit", spanish: "trucho", targetLang: "es"),
                DeckCard(english: "look/appearance", spanish: "facha", targetLang: "es"),
                DeckCard(english: "to mess around/cause trouble", spanish: "bardear", targetLang: "es"),
                DeckCard(english: "to turn a blind eye", spanish: "hacer la vista gorda", targetLang: "es"),
                DeckCard(english: "to be free/doing nothing", spanish: "estar al pedo", targetLang: "es"),
                DeckCard(english: "no way", spanish: "ni en pedo", targetLang: "es"),
                DeckCard(english: "obsession/hype", spanish: "manija", targetLang: "es"),
                DeckCard(english: "extreme/over the top", spanish: "zarpado", targetLang: "es"),
                DeckCard(english: "to look like", spanish: "tener pinta", targetLang: "es"),
                DeckCard(english: "idiot/sausage (insult)", spanish: "salame", targetLang: "es"),
                DeckCard(english: "to imagine/daydream", spanish: "flashear", targetLang: "es"),
                DeckCard(english: "cool/chill", spanish: "piola", targetLang: "es"),
                DeckCard(english: "to flirt/talk someone up", spanish: "chamuyar", targetLang: "es"),
            ]

        // MARK: - f8 Cuban Spanish (28 cards)
        case "f8":
            return [
                DeckCard(english: "buddy/dude", spanish: "asere", targetLang: "es"),
                DeckCard(english: "what's up?", spanish: "qué volá", targetLang: "es"),
                DeckCard(english: "cool/great", spanish: "chévere", targetLang: "es"),
                DeckCard(english: "bus", spanish: "guagua", targetLang: "es"),
                DeckCard(english: "bag", spanish: "jaba", targetLang: "es"),
                DeckCard(english: "dollar", spanish: "fula", targetLang: "es"),
                DeckCard(english: "to figure it out/get by", spanish: "resolver", targetLang: "es"),
                DeckCard(english: "partner/buddy", spanish: "socio", targetLang: "es"),
                DeckCard(english: "amazing/huge", spanish: "tremendo", targetLang: "es"),
                DeckCard(english: "forward/let's go", spanish: "palante", targetLang: "es"),
                DeckCard(english: "to take the bus", spanish: "coger la guagua", targetLang: "es"),
                DeckCard(english: "how amazing/outrageous", spanish: "qué bárbaro", targetLang: "es"),
                DeckCard(english: "friend", spanish: "acere", targetLang: "es"),
                DeckCard(english: "street hustler", spanish: "jinetero", targetLang: "es"),
                DeckCard(english: "gathering/party", spanish: "piquete", targetLang: "es"),
                DeckCard(english: "total mess", spanish: "arroz con mango", targetLang: "es"),
                DeckCard(english: "to be in trouble", spanish: "estar en candela", targetLang: "es"),
                DeckCard(english: "to get your act together", spanish: "ponerse las pilas", targetLang: "es"),
                DeckCard(english: "what? (expression of surprise)", spanish: "¿qué cosa?", targetLang: "es"),
                DeckCard(english: "great look/style", spanish: "tremenda pinta", targetLang: "es"),
                DeckCard(english: "goodbye", spanish: "chao", targetLang: "es"),
                DeckCard(english: "total nonsense", spanish: "puro cuento", targetLang: "es"),
                DeckCard(english: "smitten/in love", spanish: "templado", targetLang: "es"),
                DeckCard(english: "to help out", spanish: "echar un pie", targetLang: "es"),
                DeckCard(english: "let's go/start", spanish: "arranca", targetLang: "es"),
                DeckCard(english: "to excite/hype up", spanish: "embullar", targetLang: "es"),
                DeckCard(english: "to improvise/figure it out", spanish: "inventar", targetLang: "es"),
                DeckCard(english: "to party/dance", spanish: "guarachar", targetLang: "es"),
            ]

        // MARK: - f9 Business Spanish (30 cards)
        case "f9":
            return [
                DeckCard(english: "the meeting", spanish: "la reunión", targetLang: "es"),
                DeckCard(english: "the budget", spanish: "el presupuesto", targetLang: "es"),
                DeckCard(english: "the proposal", spanish: "la propuesta", targetLang: "es"),
                DeckCard(english: "the client", spanish: "el cliente", targetLang: "es"),
                DeckCard(english: "the invoice", spanish: "la factura", targetLang: "es"),
                DeckCard(english: "the contract", spanish: "el contrato", targetLang: "es"),
                DeckCard(english: "the deadline", spanish: "la fecha límite", targetLang: "es"),
                DeckCard(english: "to follow up", spanish: "hacer seguimiento", targetLang: "es"),
                DeckCard(english: "I agree", spanish: "estoy de acuerdo", targetLang: "es"),
                DeckCard(english: "I disagree", spanish: "no estoy de acuerdo", targetLang: "es"),
                DeckCard(english: "could you repeat that?", spanish: "¿podría repetirlo?", targetLang: "es"),
                DeckCard(english: "when can we meet?", spanish: "¿cuándo podemos reunirnos?", targetLang: "es"),
                DeckCard(english: "I'll send you an email", spanish: "le envío un correo", targetLang: "es"),
                DeckCard(english: "I'm attaching the file", spanish: "adjunto el archivo", targetLang: "es"),
                DeckCard(english: "awaiting response", spanish: "pendiente de respuesta", targetLang: "es"),
                DeckCard(english: "the business partner", spanish: "el socio comercial", targetLang: "es"),
                DeckCard(english: "the headquarters", spanish: "la sede", targetLang: "es"),
                DeckCard(english: "the report", spanish: "el informe", targetLang: "es"),
                DeckCard(english: "on time", spanish: "a tiempo", targetLang: "es"),
                DeckCard(english: "past the deadline", spanish: "fuera de plazo", targetLang: "es"),
                DeckCard(english: "the discount", spanish: "el descuento", targetLang: "es"),
                DeckCard(english: "the offer", spanish: "la oferta", targetLang: "es"),
                DeckCard(english: "to negotiate", spanish: "negociar", targetLang: "es"),
                DeckCard(english: "to close a deal", spanish: "cerrar un trato", targetLang: "es"),
                DeckCard(english: "underway/in progress", spanish: "en marcha", targetLang: "es"),
                DeckCard(english: "to backtrack", spanish: "dar marcha atrás", targetLang: "es"),
                DeckCard(english: "to take the lead", spanish: "tomar la delantera", targetLang: "es"),
                DeckCard(english: "the strategy", spanish: "la estrategia", targetLang: "es"),
                DeckCard(english: "the target market", spanish: "el mercado objetivo", targetLang: "es"),
                DeckCard(english: "the competition", spanish: "la competencia", targetLang: "es"),
            ]

        // MARK: - f10 Travel Emergencies (28 cards)
        case "f10":
            return [
                DeckCard(english: "help", spanish: "ayuda", targetLang: "es"),
                DeckCard(english: "call the police", spanish: "llame a la policía", targetLang: "es"),
                DeckCard(english: "I was robbed", spanish: "me robaron", targetLang: "es"),
                DeckCard(english: "I lost my passport", spanish: "perdí mi pasaporte", targetLang: "es"),
                DeckCard(english: "I need a doctor", spanish: "necesito un médico", targetLang: "es"),
                DeckCard(english: "I'm lost", spanish: "estoy perdido/a", targetLang: "es"),
                DeckCard(english: "where is the embassy?", spanish: "¿dónde está la embajada?", targetLang: "es"),
                DeckCard(english: "I feel very sick", spanish: "me siento muy mal", targetLang: "es"),
                DeckCard(english: "I need to go to the hospital", spanish: "necesito ir al hospital", targetLang: "es"),
                DeckCard(english: "it was an accident", spanish: "fue un accidente", targetLang: "es"),
                DeckCard(english: "I don't understand", spanish: "no entiendo", targetLang: "es"),
                DeckCard(english: "do you speak English?", spanish: "¿habla inglés?", targetLang: "es"),
                DeckCard(english: "call an ambulance", spanish: "llame a una ambulancia", targetLang: "es"),
                DeckCard(english: "I was attacked", spanish: "me atacaron", targetLang: "es"),
                DeckCard(english: "I lost my luggage", spanish: "perdí mi equipaje", targetLang: "es"),
                DeckCard(english: "I need to make a call", spanish: "necesito hacer una llamada", targetLang: "es"),
                DeckCard(english: "where is the police station?", spanish: "¿dónde está la estación de policía?", targetLang: "es"),
                DeckCard(english: "my card was blocked", spanish: "mi tarjeta fue bloqueada", targetLang: "es"),
                DeckCard(english: "I need an interpreter", spanish: "necesito un intérprete", targetLang: "es"),
                DeckCard(english: "I have an emergency", spanish: "tengo una emergencia", targetLang: "es"),
                DeckCard(english: "can you help me?", spanish: "¿puede ayudarme?", targetLang: "es"),
                DeckCard(english: "I don't have money", spanish: "no tengo dinero", targetLang: "es"),
                DeckCard(english: "I lost my phone", spanish: "perdí mi teléfono", targetLang: "es"),
                DeckCard(english: "is there WiFi here?", spanish: "¿hay wifi aquí?", targetLang: "es"),
                DeckCard(english: "I need to charge my phone", spanish: "necesito cargar mi teléfono", targetLang: "es"),
                DeckCard(english: "what is the address here?", spanish: "¿cuál es la dirección aquí?", targetLang: "es"),
                DeckCard(english: "someone is following me", spanish: "alguien me está siguiendo", targetLang: "es"),
                DeckCard(english: "I need to contact my embassy", spanish: "necesito contactar a mi embajada", targetLang: "es"),
            ]

        // MARK: - f11 Nightlife & Going Out (30 cards)
        case "f11":
            return [
                DeckCard(english: "where are we going?", spanish: "¿a dónde vamos?", targetLang: "es"),
                DeckCard(english: "what's the cover charge?", spanish: "¿cuál es el cover?", targetLang: "es"),
                DeckCard(english: "a round for everyone", spanish: "una ronda para todos", targetLang: "es"),
                DeckCard(english: "cheers!", spanish: "¡salud!", targetLang: "es"),
                DeckCard(english: "I'm in a good mood", spanish: "estoy de buen humor", targetLang: "es"),
                DeckCard(english: "what music do they play?", spanish: "¿qué música tocan?", targetLang: "es"),
                DeckCard(english: "what time does it close?", spanish: "¿a qué hora cierra?", targetLang: "es"),
                DeckCard(english: "there's a long line", spanish: "hay fila larga", targetLang: "es"),
                DeckCard(english: "the bartender", spanish: "el barman", targetLang: "es"),
                DeckCard(english: "a beer please", spanish: "una cerveza por favor", targetLang: "es"),
                DeckCard(english: "without ice", spanish: "sin hielo", targetLang: "es"),
                DeckCard(english: "what cocktails do you have?", spanish: "¿qué cocteles tienen?", targetLang: "es"),
                DeckCard(english: "mezcal (agave spirit)", spanish: "el mezcal", targetLang: "es"),
                DeckCard(english: "tequila", spanish: "el tequila", targetLang: "es"),
                DeckCard(english: "margarita", spanish: "la margarita", targetLang: "es"),
                DeckCard(english: "can you give me some water?", spanish: "¿me puedes dar agua?", targetLang: "es"),
                DeckCard(english: "I'm leaving now", spanish: "ya me voy", targetLang: "es"),
                DeckCard(english: "it was an incredible night", spanish: "fue una noche increíble", targetLang: "es"),
                DeckCard(english: "we're all together", spanish: "estamos todos juntos", targetLang: "es"),
                DeckCard(english: "can you watch my spot?", spanish: "¿me cuidas el lugar?", targetLang: "es"),
                DeckCard(english: "what did you think of it?", spanish: "¿qué te pareció?", targetLang: "es"),
                DeckCard(english: "it was so much fun", spanish: "fue divertidísimo", targetLang: "es"),
                DeckCard(english: "let the party continue!", spanish: "¡que siga la fiesta!", targetLang: "es"),
                DeckCard(english: "the after-party", spanish: "el after", targetLang: "es"),
                DeckCard(english: "it's already closed", spanish: "ya está cerrado", targetLang: "es"),
                DeckCard(english: "shall we go to the next place?", spanish: "¿vamos al siguiente?", targetLang: "es"),
                DeckCard(english: "let's meet here", spanish: "quedamos aquí", targetLang: "es"),
                DeckCard(english: "I got separated from the group", spanish: "me perdí del grupo", targetLang: "es"),
                DeckCard(english: "what time does the last metro leave?", spanish: "¿a qué hora sale el último metro?", targetLang: "es"),
                DeckCard(english: "see you tomorrow", spanish: "nos vemos mañana", targetLang: "es"),
            ]

        // MARK: - f12 Home & Daily Life (30 cards)
        case "f12":
            return [
                DeckCard(english: "the apartment", spanish: "el departamento", targetLang: "es"),
                DeckCard(english: "the landlord", spanish: "el casero/la casera", targetLang: "es"),
                DeckCard(english: "the tenant", spanish: "el inquilino", targetLang: "es"),
                DeckCard(english: "the rent", spanish: "la renta", targetLang: "es"),
                DeckCard(english: "to pay the rent", spanish: "pagar la renta", targetLang: "es"),
                DeckCard(english: "utilities", spanish: "los servicios", targetLang: "es"),
                DeckCard(english: "water", spanish: "el agua", targetLang: "es"),
                DeckCard(english: "electricity", spanish: "la luz", targetLang: "es"),
                DeckCard(english: "gas", spanish: "el gas", targetLang: "es"),
                DeckCard(english: "WiFi", spanish: "el wifi", targetLang: "es"),
                DeckCard(english: "the laundry", spanish: "la lavandería", targetLang: "es"),
                DeckCard(english: "to dry clothes", spanish: "secar la ropa", targetLang: "es"),
                DeckCard(english: "to go grocery shopping", spanish: "hacer las compras", targetLang: "es"),
                DeckCard(english: "the store", spanish: "la tienda", targetLang: "es"),
                DeckCard(english: "the pharmacy", spanish: "la farmacia", targetLang: "es"),
                DeckCard(english: "the bank", spanish: "el banco", targetLang: "es"),
                DeckCard(english: "the ATM", spanish: "el cajero automático", targetLang: "es"),
                DeckCard(english: "to withdraw money", spanish: "sacar dinero", targetLang: "es"),
                DeckCard(english: "to make a transfer", spanish: "hacer una transferencia", targetLang: "es"),
                DeckCard(english: "the supermarket", spanish: "el supermercado", targetLang: "es"),
                DeckCard(english: "the elevator", spanish: "el elevador", targetLang: "es"),
                DeckCard(english: "the stairs", spanish: "las escaleras", targetLang: "es"),
                DeckCard(english: "the rooftop", spanish: "la azotea", targetLang: "es"),
                DeckCard(english: "the neighbor", spanish: "el vecino/la vecina", targetLang: "es"),
                DeckCard(english: "the condo", spanish: "el condominio", targetLang: "es"),
                DeckCard(english: "the key", spanish: "la llave", targetLang: "es"),
                DeckCard(english: "the lease contract", spanish: "el contrato de arrendamiento", targetLang: "es"),
                DeckCard(english: "the trash", spanish: "la basura", targetLang: "es"),
                DeckCard(english: "what time is maintenance?", spanish: "¿a qué hora es el mantenimiento?", targetLang: "es"),
                DeckCard(english: "I'm missing something", spanish: "me falta algo", targetLang: "es"),
            ]


        case "f13":
            return [
                DeckCard(english: "Every cloud has a silver lining", spanish: "No hay mal que por bien no venga", notes: "Lit: \"There's no evil that doesn't come for good.\" Used to console someone after something bad happens — things happen for a reason and something good will follow.", targetLang: "es"),
                DeckCard(english: "Don't look a gift horse in the mouth", spanish: "A caballo regalado no se le ve el diente", notes: "Lit: \"You don't inspect the teeth of a gifted horse.\" Say this when someone complains about something they received for free.", targetLang: "es"),
                DeckCard(english: "The early bird catches the worm", spanish: "El que madruga, Dios lo ayuda", notes: "Lit: \"God helps the one who rises early.\" Encouragement to be proactive. Still said by abuelas everywhere.", targetLang: "es"),
                DeckCard(english: "Better late than never", spanish: "Más vale tarde que nunca", notes: "Direct equivalent. Used exactly the same way as in English — often said sarcastically when someone shows up late.", targetLang: "es"),
                DeckCard(english: "Silence is golden", spanish: "En boca cerrada no entran moscas", notes: "Lit: \"Flies don't enter a closed mouth.\" More vivid than the English version — the image sticks. Said when someone is talking too much or should keep a secret.", targetLang: "es"),
                DeckCard(english: "You snooze, you lose", spanish: "Camarón que se duerme, se lo lleva la corriente", notes: "Lit: \"The shrimp that falls asleep gets swept away by the current.\" One of the most uniquely Mexican expressions. Said when someone missed an opportunity by not paying attention.", targetLang: "es"),
                DeckCard(english: "Easier said than done", spanish: "Del dicho al hecho, hay mucho trecho", notes: "Lit: \"From saying to doing, there's a long stretch.\" Said when someone promises big but delivery is uncertain.", targetLang: "es"),
                DeckCard(english: "A bird in the hand is worth two in the bush", spanish: "Más vale pájaro en mano que ciento volando", notes: "Lit: \"Better a bird in hand than a hundred flying.\" Take what you have now rather than risk it for something uncertain.", targetLang: "es"),
                DeckCard(english: "He who laughs last, laughs best", spanish: "El que ríe último, ríe mejor", notes: "Direct equivalent. Said after proving someone wrong who doubted you.", targetLang: "es"),
                DeckCard(english: "Don't put all your eggs in one basket", spanish: "No pongas todos los huevos en una canasta", notes: "Direct equivalent. Financial, romantic, professional — applies everywhere.", targetLang: "es"),
                DeckCard(english: "You can't make a silk purse out of a sow's ear", spanish: "Aunque la mona se vista de seda, mona se queda", notes: "Lit: \"Even if a monkey dresses in silk, it's still a monkey.\" Blunt — used to say that you can change the exterior but not the nature of something.", targetLang: "es"),
                DeckCard(english: "You are who you hang out with", spanish: "El que con lobos anda, a aullar se enseña", notes: "Lit: \"He who runs with wolves learns to howl.\" Your environment shapes you. Said as a warning about bad influences.", targetLang: "es"),
                DeckCard(english: "This too shall pass", spanish: "No hay mal que dure cien años", notes: "Lit: \"There's no ill that lasts a hundred years.\" Comfort during hard times — nothing stays bad forever.", targetLang: "es"),
                DeckCard(english: "When life gives you lemons", spanish: "A mal tiempo, buena cara", notes: "Lit: \"To bad weather, put on a good face.\" Keep your chin up. Said to someone going through a rough patch.", targetLang: "es"),
                DeckCard(english: "All that glitters is not gold", spanish: "No todo lo que brilla es oro", notes: "Direct equivalent. Don't be fooled by appearances.", targetLang: "es"),
                DeckCard(english: "Greed is its own punishment", spanish: "La avaricia rompe el saco", notes: "Lit: \"Greed breaks the bag.\" When you try to take too much, you end up with nothing.", targetLang: "es"),
                DeckCard(english: "None so blind as those who won't see", spanish: "No hay peor sordo que el que no quiere oír", notes: "Lit: \"There's no worse deaf person than one who refuses to hear.\" Said about someone who ignores the truth because it's inconvenient.", targetLang: "es"),
                DeckCard(english: "Many a true word is spoken in jest", spanish: "Entre broma y broma, la verdad se asoma", notes: "Lit: \"Between joke and joke, the truth peeks out.\" What people say \\\"just kidding\\\" about is often what they really mean.", targetLang: "es"),
                DeckCard(english: "Don't put off till tomorrow what you can do today", spanish: "No dejes para mañana lo que puedes hacer hoy", notes: "Direct equivalent. Said with mild exasperation when someone is procrastinating.", targetLang: "es"),
                DeckCard(english: "Show me your friends, I'll show you who you are", spanish: "Dime con quién andas y te diré quién eres", notes: "Lit: \"Tell me who you walk with and I'll tell you who you are.\" One of the most commonly used in Mexico.", targetLang: "es"),
            ]

        case "f14":
            return [
                DeckCard(english: "To have sex", spanish: "Echar un polvo", notes: "Lit: \"To throw some dust.\" Very widely used, mildly vulgar but said casually between adults. Equivalent to \"getting laid.\"", targetLang: "es"),
                DeckCard(english: "To flirt aggressively", spanish: "Tirar los perros", notes: "Lit: \"To throw the dogs at someone.\" \"Me estaba tirando los perros\" = He/she was hitting on me hard. Mexico and Central America.", targetLang: "es"),
                DeckCard(english: "To get completely wasted", spanish: "Ponerse hasta las chanclas", notes: "Lit: \"To get up to your flip-flops.\" Vivid image. More colorful than just \"borracho.\"", targetLang: "es"),
                DeckCard(english: "To be drunk", spanish: "Estar pedo", notes: "Lit: \"To be a fart.\" One of Mexico's most common slang terms for drunk. Also \"estar bien pedo\" = totally hammered.", targetLang: "es"),
                DeckCard(english: "Foreplay / warming up", spanish: "Calentar los motores", notes: "Lit: \"To warm up the engines.\" Can be used literally (warming up before exercise) or euphemistically for physical intimacy.", targetLang: "es"),
                DeckCard(english: "To hook up / make out", spanish: "Enrollarse", notes: "\"Se enrollaron en la fiesta\" = They hooked up at the party. Spain-origin but used across Latin America.", targetLang: "es"),
                DeckCard(english: "Heavy making out", spanish: "Darse el lote", notes: "Lit: \"To give each other the lot.\" More intense than enrollarse. Used mostly by younger speakers.", targetLang: "es"),
                DeckCard(english: "To get lucky / eat a lot", spanish: "Ponerse las botas", notes: "Lit: \"To put on your boots.\" Dual meaning — eating very well OR getting lucky sexually. Context tells you which.", targetLang: "es"),
                DeckCard(english: "To be in a bad mood", spanish: "Tener mala leche", notes: "Lit: \"To have bad milk.\" Vulgar origin but said casually. \"Hoy amaneció con mala leche\" = He woke up on the wrong side of the bed.", targetLang: "es"),
                DeckCard(english: "To go on a bender", spanish: "Irse de juerga", notes: "\"Se fueron de juerga toda la semana\" = They partied all week. Not just one night out.", targetLang: "es"),
                DeckCard(english: "To be hungover", spanish: "Estar crudo", notes: "Lit: \"To be raw.\" One of Mexico's most useful words. \"Estoy muy crudo\" = I'm so hungover.", targetLang: "es"),
                DeckCard(english: "To go all in / go hard", spanish: "Meterle caña", notes: "Lit: \"To put in the sugarcane.\" \"Hay que meterle caña al proyecto\" = We need to really push this project.", targetLang: "es"),
                DeckCard(english: "To have a lot of nerve", spanish: "Tener mucha cara", notes: "Lit: \"To have a lot of face.\" \"Tiene mucha cara ese tipo\" = That guy has some nerve.", targetLang: "es"),
                DeckCard(english: "To crash / go to bed", spanish: "Irse al sobre", notes: "Lit: \"To go to the envelope.\" Said when you're exhausted and heading to bed. \"Me voy al sobre\" = I'm crashing.", targetLang: "es"),
                DeckCard(english: "In the middle of nowhere", spanish: "Estar en el quinto pino", notes: "Lit: \"At the fifth pine tree.\" Far away, difficult to reach. \"Su casa está en el quinto pino\" = His house is in the absolute middle of nowhere.", targetLang: "es"),
                DeckCard(english: "To have a thing going on", spanish: "Tener rollo", notes: "\"Tienen rollo\" = There's something going on between them. Ambiguous, which is the point.", targetLang: "es"),
                DeckCard(english: "To hit the jackpot", spanish: "Sacarse el gordo", notes: "Lit: \"To pull out the fat one.\" Could be literal (lottery) or metaphorical (meeting someone amazing).", targetLang: "es"),
                DeckCard(english: "To cross the line", spanish: "Pasarse de la raya", notes: "Lit: \"To go past the line.\" \"Se pasó de la raya\" = He went too far. Widely used, socially and physically.", targetLang: "es"),
                DeckCard(english: "To lose your mind", spanish: "Írsele la olla", notes: "Lit: \"The pot walks away from you.\" \"Se le fue la olla\" = She lost her mind / went off the rails.", targetLang: "es"),
                DeckCard(english: "To make a move / strike", spanish: "Dar el golpe", notes: "Lit: \"To land the hit.\" Used when someone makes a bold move romantically or professionally. \"Dale el golpe ya\" = Just make your move already.", targetLang: "es"),
            ]

        case "f15":
            return [
                DeckCard(english: "Love at first sight", spanish: "Flechazo", notes: "Lit: \"Arrow hit.\" The exact moment Cupid's arrow lands. \"Fue un flechazo\" = It was instant.", targetLang: "es"),
                DeckCard(english: "Soulmate / other half", spanish: "Media naranja", notes: "Lit: \"Half orange.\" The idea that you're half and your partner completes you. Widely used in everyday speech.", targetLang: "es"),
                DeckCard(english: "To have chemistry", spanish: "Tener química", notes: "Direct equivalent. \"Tenemos mucha química\" = We have great chemistry.", targetLang: "es"),
                DeckCard(english: "To flirt / pick someone up", spanish: "Ligar", notes: "\"Fue al bar a ligar\" = He went to the bar to pick someone up. More direct than coquetear.", targetLang: "es"),
                DeckCard(english: "To flirt", spanish: "Coquetear", notes: "Lighter, more playful than ligar. Like batting your eyelashes. \"Estaba coqueteando con él\" = She was flirting with him.", targetLang: "es"),
                DeckCard(english: "You have an incredible smile", spanish: "Tienes una sonrisa increíble", notes: "A compliment safe to use with anyone, any gender. Reliable opener that doesn't feel aggressive.", targetLang: "es"),
                DeckCard(english: "Can I have your number?", spanish: "¿Me das tu número?", notes: "The standard ask. Direct, no games. Works every time it's going to work.", targetLang: "es"),
                DeckCard(english: "To be dating someone", spanish: "Salir con alguien", notes: "\"Estoy saliendo con alguien\" = I'm seeing someone. The neutral way to say you're seeing someone.", targetLang: "es"),
                DeckCard(english: "I really like you", spanish: "Me encantas", notes: "Stronger than \"me gustas.\" Used when feelings are real. \"Me encantas\" lands with weight.", targetLang: "es"),
                DeckCard(english: "To be in love", spanish: "Estar enamorado/a", notes: "\"Estoy enamorado\" (m) / \"Estoy enamorada\" (f). Gender-inflected. Both mean the same thing — I'm in love.", targetLang: "es"),
                DeckCard(english: "To be going out with someone", spanish: "Andar con alguien", notes: "MX-specific. \"Ando con ella\" = I'm going out with her. Casual relationship status.", targetLang: "es"),
                DeckCard(english: "To have a date", spanish: "Tener una cita", notes: "\"Tengo una cita esta noche\" = I have a date tonight.", targetLang: "es"),
                DeckCard(english: "To make up after a fight", spanish: "Hacer las paces", notes: "Lit: \"To make the peaces.\" The reconciliation moment after an argument. \"Ya hicimos las paces\" = We made up.", targetLang: "es"),
                DeckCard(english: "Long distance relationship", spanish: "Relación a distancia", notes: "Direct equivalent. Comes with the same eye rolls in any language.", targetLang: "es"),
                DeckCard(english: "To be exclusive", spanish: "Ser exclusivos", notes: "\"¿Somos exclusivos?\" = Are we exclusive? The \"what are we?\" conversation outcome.", targetLang: "es"),
                DeckCard(english: "To reject / ghost someone", spanish: "Dar calabazas", notes: "Lit: \"To give them pumpkins.\" The calabaza is historically a symbol of rejection in Spanish. \"Me dio calabazas\" = She rejected me.", targetLang: "es"),
                DeckCard(english: "To be crazy about someone", spanish: "Estar colado/a", notes: "\"Estoy colado por ella\" (m) / \"Estoy colada por él\" (f). Lit: \"to be filtered through\" — implies you can't think straight.", targetLang: "es"),
                DeckCard(english: "To confess your feelings", spanish: "Declararse", notes: "\"Se declaró\" = He/she made their feelings known. A bigger deal than just flirting.", targetLang: "es"),
                DeckCard(english: "Courtship", spanish: "Cortejo", notes: "The old-school pursuit. Still used, often with gentle irony. \"Está en modo cortejo\" = He's in full courtship mode.", targetLang: "es"),
                DeckCard(english: "To have butterflies", spanish: "Tener mariposas", notes: "\"Cuando lo veo tengo mariposas\" = When I see him I get butterflies. Direct equivalent, same usage.", targetLang: "es"),
            ]

        default:
            return []
        }
    }
    // swiftlint:enable function_body_length
}
