//
//  FeaturedDeckContent.swift
//  TranslateHelper
//
//  Static card content for all featured decks (f1–f12).
//

import Foundation

struct FeaturedDeckContent {

    // swiftlint:disable function_body_length
    static func cards(forId id: String) -> [DeckCard] {
        switch id {

        // MARK: - f1 Mexico City Slang (50 cards)
        case "f1":
            return [
                DeckCard(english: "cool/awesome", spanish: "chido/a"),
                DeckCard(english: "beer", spanish: "chela"),
                DeckCard(english: "buddy/friend", spanish: "cuate"),
                DeckCard(english: "dude (very common)", spanish: "güey"),
                DeckCard(english: "wow/oh man", spanish: "híjole"),
                DeckCard(english: "come on/alright", spanish: "ándale"),
                DeckCard(english: "right on/let's go", spanish: "órale"),
                DeckCard(english: "cheap/bad quality", spanish: "chafa"),
                DeckCard(english: "money (slang)", spanish: "feria"),
                DeckCard(english: "money", spanish: "lana"),
                DeckCard(english: "work/job", spanish: "jale"),
                DeckCard(english: "truth/for real", spanish: "neta"),
                DeckCard(english: "hell yeah", spanish: "a huevo"),
                DeckCard(english: "no way/come on", spanish: "no manches"),
                DeckCard(english: "good vibes", spanish: "buena onda"),
                DeckCard(english: "bad vibes", spanish: "mala onda"),
                DeckCard(english: "amazed/shocked", spanish: "curado"),
                DeckCard(english: "I like them (they're cool)", spanish: "me cae"),
                DeckCard(english: "I don't like them", spanish: "no me cae"),
                DeckCard(english: "it's tough/intense", spanish: "está cañón"),
                DeckCard(english: "I don't care", spanish: "me vale"),
                DeckCard(english: "right now (or maybe later — very ambiguous!)", spanish: "ahorita"),
                DeckCard(english: "honestly/for real", spanish: "al chile"),
                DeckCard(english: "problem/issue", spanish: "pedo"),
                DeckCard(english: "to be drunk", spanish: "estar pedo"),
                DeckCard(english: "what's up/what's the deal", spanish: "qué pedo"),
                DeckCard(english: "to play along with someone", spanish: "dar el avión"),
                DeckCard(english: "close friend/bro", spanish: "carnal"),
                DeckCard(english: "problem/bind", spanish: "clavo"),
                DeckCard(english: "fast/urgently", spanish: "en chinga"),
                DeckCard(english: "badass/awesome", spanish: "chingón"),
                DeckCard(english: "awesome/skilled", spanish: "fregón"),
                DeckCard(english: "bad/ugly/mean", spanish: "gacho"),
                DeckCard(english: "to leave/take off", spanish: "jalarse"),
                DeckCard(english: "no way/absolutely not", spanish: "ni madres"),
                DeckCard(english: "what's up?", spanish: "qué onda"),
                DeckCard(english: "it cracked me up", spanish: "me raía"),
                DeckCard(english: "yes (slang)", spanish: "simon"),
                DeckCard(english: "no (slang)", spanish: "nel"),
                DeckCard(english: "later/goodbye", spanish: "pa' luego"),
                DeckCard(english: "to drink alcohol", spanish: "pistear"),
                DeckCard(english: "hungover", spanish: "crudo"),
                DeckCard(english: "damn (intensifier)", spanish: "pinche"),
                DeckCard(english: "shady deal/person", spanish: "transa"),
                DeckCard(english: "kid/brat", spanish: "escuincle"),
                DeckCard(english: "morbid curiosity/drama", spanish: "morbo"),
                DeckCard(english: "to give someone a lift", spanish: "dar un ride"),
                DeckCard(english: "person from CDMX", spanish: "chilango"),
                DeckCard(english: "work/job (synonym for jale)", spanish: "chamba"),
                DeckCard(english: "to be at 100%/feeling great", spanish: "estar al cien"),
            ]

        // MARK: - f2 Romantic Phrases (40 cards)
        case "f2":
            return [
                DeckCard(english: "I like you/love you (warm but not deep)", spanish: "te quiero"),
                DeckCard(english: "I love you (deep love)", spanish: "te amo"),
                DeckCard(english: "I like you romantically", spanish: "me gustas"),
                DeckCard(english: "you're very handsome/beautiful", spanish: "eres muy guapo/a"),
                DeckCard(english: "do you have a boyfriend/girlfriend?", spanish: "¿tienes novio/a?"),
                DeckCard(english: "do you want to go out with me?", spanish: "¿quieres salir conmigo?"),
                DeckCard(english: "you drive me crazy", spanish: "me vuelves loco/a"),
                DeckCard(english: "you're my other half", spanish: "eres mi media naranja"),
                DeckCard(english: "I miss you", spanish: "te extraño"),
                DeckCard(english: "I think about you", spanish: "pienso en ti"),
                DeckCard(english: "you make me very happy", spanish: "me haces muy feliz"),
                DeckCard(english: "can I have your number?", spanish: "¿me das tu número?"),
                DeckCard(english: "you're incredible", spanish: "eres increíble"),
                DeckCard(english: "I'm crazy about you", spanish: "me encantas"),
                DeckCard(english: "you have beautiful eyes", spanish: "tienes ojos hermosos"),
                DeckCard(english: "do you want to be my boyfriend/girlfriend?", spanish: "¿quieres ser mi novio/a?"),
                DeckCard(english: "I'm in love with you", spanish: "estoy enamorado/a de ti"),
                DeckCard(english: "I can't live without you", spanish: "no puedo vivir sin ti"),
                DeckCard(english: "you're the best thing that's happened to me", spanish: "eres lo mejor que me ha pasado"),
                DeckCard(english: "when can I see you again?", spanish: "¿cuándo te puedo ver de nuevo?"),
                DeckCard(english: "you have me on cloud nine", spanish: "me tienes en las nubes"),
                DeckCard(english: "you're my favourite person", spanish: "eres mi persona favorita"),
                DeckCard(english: "my heart (endearment)", spanish: "mi corazón"),
                DeckCard(english: "my love", spanish: "amor mío"),
                DeckCard(english: "darling/honey", spanish: "cariño"),
                DeckCard(english: "sweetheart (lit: sky)", spanish: "cielo"),
                DeckCard(english: "baby (endearment)", spanish: "bebé"),
                DeckCard(english: "give me a hug", spanish: "dame un abrazo"),
                DeckCard(english: "can I have a kiss?", spanish: "¿me das un beso?"),
                DeckCard(english: "I'm nervous", spanish: "estoy nervioso/a"),
                DeckCard(english: "you make me nervous", spanish: "me pones nervioso/a"),
                DeckCard(english: "I want to know you better", spanish: "quiero conocerte mejor"),
                DeckCard(english: "you're special to me", spanish: "eres especial para mí"),
                DeckCard(english: "I'd like to invite you to dinner", spanish: "me gustaría invitarte a cenar"),
                DeckCard(english: "I have butterflies in my stomach", spanish: "tengo mariposas en el estómago"),
                DeckCard(english: "I really liked meeting you", spanish: "me gustó mucho conocerte"),
                DeckCard(english: "where have you been all my life?", spanish: "¿dónde has estado toda mi vida?"),
                DeckCard(english: "I'll always be here for you", spanish: "siempre estaré aquí para ti"),
                DeckCard(english: "you're perfectly imperfect", spanish: "eres perfectamente imperfecto/a"),
                DeckCard(english: "you and me against the world", spanish: "tú y yo contra el mundo"),
            ]

        // MARK: - f3 Medical Spanish (60 cards)
        case "f3":
            return [
                DeckCard(english: "it hurts", spanish: "me duele"),
                DeckCard(english: "I have a headache", spanish: "me duele la cabeza"),
                DeckCard(english: "my stomach hurts", spanish: "me duele el estómago"),
                DeckCard(english: "I have a fever", spanish: "tengo fiebre"),
                DeckCard(english: "I have a cough", spanish: "tengo tos"),
                DeckCard(english: "my throat hurts", spanish: "me duele la garganta"),
                DeckCard(english: "I feel nauseous", spanish: "tengo náuseas"),
                DeckCard(english: "I vomited", spanish: "vomité"),
                DeckCard(english: "I have diarrhea", spanish: "tengo diarrea"),
                DeckCard(english: "I'm dizzy", spanish: "estoy mareado/a"),
                DeckCard(english: "I cut myself", spanish: "me corté"),
                DeckCard(english: "I fell", spanish: "me caí"),
                DeckCard(english: "I twisted my ankle", spanish: "me torcí el tobillo"),
                DeckCard(english: "I'm allergic to...", spanish: "soy alérgico/a a..."),
                DeckCard(english: "I take medication for...", spanish: "tomo medicamentos para..."),
                DeckCard(english: "I'm diabetic", spanish: "soy diabético/a"),
                DeckCard(english: "I have high blood pressure", spanish: "tengo presión alta"),
                DeckCard(english: "I need a doctor", spanish: "necesito un médico"),
                DeckCard(english: "call an ambulance", spanish: "llame a una ambulancia"),
                DeckCard(english: "where is the pharmacy?", spanish: "¿dónde está la farmacia?"),
                DeckCard(english: "I need this prescription", spanish: "necesito esta receta"),
                DeckCard(english: "do you have something for pain?", spanish: "¿tiene algo para el dolor?"),
                DeckCard(english: "pills/tablets", spanish: "pastillas"),
                DeckCard(english: "medicine syrup", spanish: "jarabe"),
                DeckCard(english: "the doctor's consultation", spanish: "la consulta"),
                DeckCard(english: "the doctor", spanish: "el médico"),
                DeckCard(english: "the hospital", spanish: "el hospital"),
                DeckCard(english: "the emergency room", spanish: "la sala de emergencias"),
                DeckCard(english: "the clinic", spanish: "la clínica"),
                DeckCard(english: "insurance", spanish: "el seguro"),
                DeckCard(english: "the prescription", spanish: "la receta"),
                DeckCard(english: "the blood test", spanish: "el análisis de sangre"),
                DeckCard(english: "blood pressure", spanish: "la presión arterial"),
                DeckCard(english: "the heart", spanish: "el corazón"),
                DeckCard(english: "the lung", spanish: "el pulmón"),
                DeckCard(english: "the liver", spanish: "el hígado"),
                DeckCard(english: "the knee", spanish: "la rodilla"),
                DeckCard(english: "the ankle", spanish: "el tobillo"),
                DeckCard(english: "the back", spanish: "la espalda"),
                DeckCard(english: "the chest", spanish: "el pecho"),
                DeckCard(english: "the wrist", spanish: "la muñeca"),
                DeckCard(english: "the hip", spanish: "la cadera"),
                DeckCard(english: "the head", spanish: "la cabeza"),
                DeckCard(english: "the throat", spanish: "la garganta"),
                DeckCard(english: "the arm", spanish: "el brazo"),
                DeckCard(english: "the leg", spanish: "la pierna"),
                DeckCard(english: "I feel very sick", spanish: "me siento muy mal"),
                DeckCard(english: "I have chills", spanish: "tengo escalofríos"),
                DeckCard(english: "I can't breathe well", spanish: "no puedo respirar bien"),
                DeckCard(english: "do you have English-speaking doctors?", spanish: "¿tiene médicos que hablen inglés?"),
                DeckCard(english: "the deductible/copay", spanish: "el deducible"),
                DeckCard(english: "antibiotics", spanish: "antibióticos"),
                DeckCard(english: "paracetamol/acetaminophen", spanish: "paracetamol"),
                DeckCard(english: "ibuprofen", spanish: "ibuprofeno"),
                DeckCard(english: "cream/ointment", spanish: "crema"),
                DeckCard(english: "I need water", spanish: "necesito agua"),
                DeckCard(english: "I have chest pain", spanish: "tengo dolor de pecho"),
                DeckCard(english: "it hurts when I breathe", spanish: "me duele al respirar"),
                DeckCard(english: "I lost consciousness", spanish: "perdí el conocimiento"),
                DeckCard(english: "I have an infection", spanish: "tengo una infección"),
            ]

        // MARK: - f4 Food & Markets (40 cards)
        case "f4":
            return [
                DeckCard(english: "the bill please", spanish: "la cuenta por favor"),
                DeckCard(english: "what do you recommend?", spanish: "¿qué recomienda?"),
                DeckCard(english: "without spice please", spanish: "sin picante por favor"),
                DeckCard(english: "very spicy", spanish: "muy picante"),
                DeckCard(english: "is the tip included?", spanish: "¿está incluido el servicio?"),
                DeckCard(english: "to go", spanish: "para llevar"),
                DeckCard(english: "to eat here", spanish: "para comer aquí"),
                DeckCard(english: "do you have vegetarian options?", spanish: "¿tiene opciones vegetarianas?"),
                DeckCard(english: "I'm vegetarian", spanish: "soy vegetariano/a"),
                DeckCard(english: "gluten-free", spanish: "sin gluten"),
                DeckCard(english: "tacos", spanish: "tacos"),
                DeckCard(english: "quesadillas", spanish: "quesadillas"),
                DeckCard(english: "tamales", spanish: "tamales"),
                DeckCard(english: "hearty hominy soup", spanish: "pozole"),
                DeckCard(english: "fried tortillas in salsa with egg", spanish: "chilaquiles"),
                DeckCard(english: "corn tortilla", spanish: "la tortilla de maíz"),
                DeckCard(english: "sauce/salsa", spanish: "la salsa"),
                DeckCard(english: "chili pepper", spanish: "el chile"),
                DeckCard(english: "lime (in Mexico limón = lime)", spanish: "el limón"),
                DeckCard(english: "sour cream", spanish: "la crema"),
                DeckCard(english: "cheese", spanish: "el queso"),
                DeckCard(english: "avocado", spanish: "el aguacate"),
                DeckCard(english: "beans", spanish: "los frijoles"),
                DeckCard(english: "rice", spanish: "el arroz"),
                DeckCard(english: "the market", spanish: "el mercado"),
                DeckCard(english: "how much is it?", spanish: "¿cuánto cuesta?"),
                DeckCard(english: "can I have a kilo of...?", spanish: "¿me da un kilo de...?"),
                DeckCard(english: "it's very expensive", spanish: "está muy caro"),
                DeckCard(english: "do you have change?", spanish: "¿tiene cambio?"),
                DeckCard(english: "the market stall", spanish: "el puesto"),
                DeckCard(english: "corn on the cob", spanish: "elote"),
                DeckCard(english: "corn in a cup with mayo cheese and chili", spanish: "esquites"),
                DeckCard(english: "slow-cooked spiced meat stew", spanish: "la birria"),
                DeckCard(english: "ceviche-style marinated shrimp", spanish: "el aguachile"),
                DeckCard(english: "beer with lime juice and spices", spanish: "el michelada"),
                DeckCard(english: "basket taco (steamed, sold on street)", spanish: "el taco de canasta"),
                DeckCard(english: "scrambled eggs", spanish: "huevos revueltos"),
                DeckCard(english: "sweet bread (Mexican pastry)", spanish: "el pan dulce"),
                DeckCard(english: "traditional Mexican pot coffee", spanish: "el café de olla"),
                DeckCard(english: "warm corn-based drink", spanish: "atole"),
            ]

        // MARK: - f5 Flirting & Banter (34 cards)
        case "f5":
            return [
                DeckCard(english: "you're very hot", spanish: "estás muy bueno/a"),
                DeckCard(english: "you have great vibes", spanish: "tienes muy buena vibra"),
                DeckCard(english: "are you from here?", spanish: "¿eres de aquí?"),
                DeckCard(english: "where are you from?", spanish: "¿de dónde eres?"),
                DeckCard(english: "I really like you (personality)", spanish: "me caes muy bien"),
                DeckCard(english: "you're very funny", spanish: "eres muy chistoso/a"),
                DeckCard(english: "you make me laugh", spanish: "me haces reír"),
                DeckCard(english: "what are you doing right now?", spanish: "¿qué estás haciendo ahorita?"),
                DeckCard(english: "do you want to get a drink?", spanish: "¿quieres tomar algo?"),
                DeckCard(english: "you're very interesting", spanish: "eres muy interesante"),
                DeckCard(english: "you caught my attention", spanish: "me llama la atención"),
                DeckCard(english: "you have great style", spanish: "tienes mucho estilo"),
                DeckCard(english: "do you dance?", spanish: "¿bailas?"),
                DeckCard(english: "will you teach me to dance?", spanish: "¿me enseñas a bailar?"),
                DeckCard(english: "what are you doing this weekend?", spanish: "¿qué haces el fin de semana?"),
                DeckCard(english: "we have to hang out", spanish: "tenemos que salir"),
                DeckCard(english: "I liked you from the moment I saw you", spanish: "me gustas desde que te vi"),
                DeckCard(english: "you're always on my mind", spanish: "siempre estás en mi mente"),
                DeckCard(english: "don't be shy", spanish: "no seas tímido/a"),
                DeckCard(english: "tell me about yourself", spanish: "platícame de ti"),
                DeckCard(english: "you have an incredible smile", spanish: "tienes una sonrisa increíble"),
                DeckCard(english: "I love your eyes", spanish: "me encantan tus ojos"),
                DeckCard(english: "are you single?", spanish: "¿eres soltero/a?"),
                DeckCard(english: "I won't bite (playful)", spanish: "no te voy a morder"),
                DeckCard(english: "you're a delight/charmer", spanish: "eres un encanto"),
                DeckCard(english: "will you give me a chance?", spanish: "¿me das chance?"),
                DeckCard(english: "we have chemistry", spanish: "tenemos química"),
                DeckCard(english: "I won't forget you tonight", spanish: "esta noche no te olvido"),
                DeckCard(english: "you look really good", spanish: "te ves muy bien"),
                DeckCard(english: "you're my type", spanish: "eres mi tipo"),
                DeckCard(english: "what do you do for work?", spanish: "¿a qué te dedicas?"),
                DeckCard(english: "I like you a lot", spanish: "me gustas mucho"),
                DeckCard(english: "will you join me?", spanish: "¿me acompañas?"),
                DeckCard(english: "you look so handsome/beautiful today", spanish: "qué guapo/a estás hoy"),
            ]

        // MARK: - f6 Sports & Fútbol (36 cards)
        case "f6":
            return [
                DeckCard(english: "the match/game", spanish: "el partido"),
                DeckCard(english: "the goal", spanish: "el gol"),
                DeckCard(english: "the goalkeeper", spanish: "el portero"),
                DeckCard(english: "the forward/striker", spanish: "el delantero"),
                DeckCard(english: "the midfielder", spanish: "el mediocampista"),
                DeckCard(english: "the defender", spanish: "el defensa"),
                DeckCard(english: "the referee", spanish: "el árbitro"),
                DeckCard(english: "the red card", spanish: "la tarjeta roja"),
                DeckCard(english: "the yellow card", spanish: "la tarjeta amarilla"),
                DeckCard(english: "the penalty kick", spanish: "el penal"),
                DeckCard(english: "the corner kick", spanish: "el tiro de esquina"),
                DeckCard(english: "offside", spanish: "el fuera de lugar"),
                DeckCard(english: "the field/pitch", spanish: "la cancha"),
                DeckCard(english: "the stands", spanish: "la tribuna"),
                DeckCard(english: "the stadium", spanish: "el estadio"),
                DeckCard(english: "the coach/manager", spanish: "el entrenador"),
                DeckCard(english: "he/she scored a goal", spanish: "metió un gol"),
                DeckCard(english: "amazing goal!", spanish: "¡golazo!"),
                DeckCard(english: "it's tied", spanish: "está empatado"),
                DeckCard(english: "we're winning", spanish: "vamos ganando"),
                DeckCard(english: "we're losing", spanish: "vamos perdiendo"),
                DeckCard(english: "the score", spanish: "el marcador"),
                DeckCard(english: "extra time", spanish: "el tiempo extra"),
                DeckCard(english: "penalty shootout", spanish: "los penales"),
                DeckCard(english: "the fan", spanish: "el aficionado"),
                DeckCard(english: "the national team", spanish: "la selección"),
                DeckCard(english: "Club América (CDMX team)", spanish: "el América"),
                DeckCard(english: "Guadalajara/Chivas", spanish: "las Chivas"),
                DeckCard(english: "Mexico national team", spanish: "el Tri"),
                DeckCard(english: "come on Mexico!", spanish: "¡arriba México!"),
                DeckCard(english: "what's the score?", spanish: "¿cómo va el marcador?"),
                DeckCard(english: "he/she is playing very well", spanish: "está jugando muy bien"),
                DeckCard(english: "the league", spanish: "la liga"),
                DeckCard(english: "the championship", spanish: "el campeonato"),
                DeckCard(english: "Mexico Cup", spanish: "la Copa MX"),
                DeckCard(english: "the derby/classic rivalry match", spanish: "el clásico"),
            ]

        // MARK: - f7 Argentine Slang (30 cards)
        case "f7":
            return [
                DeckCard(english: "dude/idiot (friendly)", spanish: "boludo"),
                DeckCard(english: "hey/mate", spanish: "che"),
                DeckCard(english: "cool/awesome", spanish: "copado"),
                DeckCard(english: "work/job", spanish: "laburo"),
                DeckCard(english: "to eat", spanish: "morfar"),
                DeckCard(english: "kid/guy", spanish: "pibe"),
                DeckCard(english: "girl/woman", spanish: "mina"),
                DeckCard(english: "mess/chaos", spanish: "quilombo"),
                DeckCard(english: "very (intensifier)", spanish: "re"),
                DeckCard(english: "beer", spanish: "birra"),
                DeckCard(english: "laziness", spanish: "fiaca"),
                DeckCard(english: "sweet talk/flirting", spanish: "chamullo"),
                DeckCard(english: "to pay", spanish: "garpar"),
                DeckCard(english: "police", spanish: "cana"),
                DeckCard(english: "to steal", spanish: "afanar"),
                DeckCard(english: "dude/guy", spanish: "chabón"),
                DeckCard(english: "for real/truth", spanish: "posta"),
                DeckCard(english: "fake/counterfeit", spanish: "trucho"),
                DeckCard(english: "look/appearance", spanish: "facha"),
                DeckCard(english: "to mess around/cause trouble", spanish: "bardear"),
                DeckCard(english: "to turn a blind eye", spanish: "hacer la vista gorda"),
                DeckCard(english: "to be free/doing nothing", spanish: "estar al pedo"),
                DeckCard(english: "no way", spanish: "ni en pedo"),
                DeckCard(english: "obsession/hype", spanish: "manija"),
                DeckCard(english: "extreme/over the top", spanish: "zarpado"),
                DeckCard(english: "to look like", spanish: "tener pinta"),
                DeckCard(english: "idiot/sausage (insult)", spanish: "salame"),
                DeckCard(english: "to imagine/daydream", spanish: "flashear"),
                DeckCard(english: "cool/chill", spanish: "piola"),
                DeckCard(english: "to flirt/talk someone up", spanish: "chamuyar"),
            ]

        // MARK: - f8 Cuban Spanish (28 cards)
        case "f8":
            return [
                DeckCard(english: "buddy/dude", spanish: "asere"),
                DeckCard(english: "what's up?", spanish: "qué volá"),
                DeckCard(english: "cool/great", spanish: "chévere"),
                DeckCard(english: "bus", spanish: "guagua"),
                DeckCard(english: "bag", spanish: "jaba"),
                DeckCard(english: "dollar", spanish: "fula"),
                DeckCard(english: "to figure it out/get by", spanish: "resolver"),
                DeckCard(english: "partner/buddy", spanish: "socio"),
                DeckCard(english: "amazing/huge", spanish: "tremendo"),
                DeckCard(english: "forward/let's go", spanish: "palante"),
                DeckCard(english: "to take the bus", spanish: "coger la guagua"),
                DeckCard(english: "how amazing/outrageous", spanish: "qué bárbaro"),
                DeckCard(english: "friend", spanish: "acere"),
                DeckCard(english: "street hustler", spanish: "jinetero"),
                DeckCard(english: "gathering/party", spanish: "piquete"),
                DeckCard(english: "total mess", spanish: "arroz con mango"),
                DeckCard(english: "to be in trouble", spanish: "estar en candela"),
                DeckCard(english: "to get your act together", spanish: "ponerse las pilas"),
                DeckCard(english: "what? (expression of surprise)", spanish: "¿qué cosa?"),
                DeckCard(english: "great look/style", spanish: "tremenda pinta"),
                DeckCard(english: "goodbye", spanish: "chao"),
                DeckCard(english: "total nonsense", spanish: "puro cuento"),
                DeckCard(english: "smitten/in love", spanish: "templado"),
                DeckCard(english: "to help out", spanish: "echar un pie"),
                DeckCard(english: "let's go/start", spanish: "arranca"),
                DeckCard(english: "to excite/hype up", spanish: "embullar"),
                DeckCard(english: "to improvise/figure it out", spanish: "inventar"),
                DeckCard(english: "to party/dance", spanish: "guarachar"),
            ]

        // MARK: - f9 Business Spanish (30 cards)
        case "f9":
            return [
                DeckCard(english: "the meeting", spanish: "la reunión"),
                DeckCard(english: "the budget", spanish: "el presupuesto"),
                DeckCard(english: "the proposal", spanish: "la propuesta"),
                DeckCard(english: "the client", spanish: "el cliente"),
                DeckCard(english: "the invoice", spanish: "la factura"),
                DeckCard(english: "the contract", spanish: "el contrato"),
                DeckCard(english: "the deadline", spanish: "la fecha límite"),
                DeckCard(english: "to follow up", spanish: "hacer seguimiento"),
                DeckCard(english: "I agree", spanish: "estoy de acuerdo"),
                DeckCard(english: "I disagree", spanish: "no estoy de acuerdo"),
                DeckCard(english: "could you repeat that?", spanish: "¿podría repetirlo?"),
                DeckCard(english: "when can we meet?", spanish: "¿cuándo podemos reunirnos?"),
                DeckCard(english: "I'll send you an email", spanish: "le envío un correo"),
                DeckCard(english: "I'm attaching the file", spanish: "adjunto el archivo"),
                DeckCard(english: "awaiting response", spanish: "pendiente de respuesta"),
                DeckCard(english: "the business partner", spanish: "el socio comercial"),
                DeckCard(english: "the headquarters", spanish: "la sede"),
                DeckCard(english: "the report", spanish: "el informe"),
                DeckCard(english: "on time", spanish: "a tiempo"),
                DeckCard(english: "past the deadline", spanish: "fuera de plazo"),
                DeckCard(english: "the discount", spanish: "el descuento"),
                DeckCard(english: "the offer", spanish: "la oferta"),
                DeckCard(english: "to negotiate", spanish: "negociar"),
                DeckCard(english: "to close a deal", spanish: "cerrar un trato"),
                DeckCard(english: "underway/in progress", spanish: "en marcha"),
                DeckCard(english: "to backtrack", spanish: "dar marcha atrás"),
                DeckCard(english: "to take the lead", spanish: "tomar la delantera"),
                DeckCard(english: "the strategy", spanish: "la estrategia"),
                DeckCard(english: "the target market", spanish: "el mercado objetivo"),
                DeckCard(english: "the competition", spanish: "la competencia"),
            ]

        // MARK: - f10 Travel Emergencies (28 cards)
        case "f10":
            return [
                DeckCard(english: "help", spanish: "ayuda"),
                DeckCard(english: "call the police", spanish: "llame a la policía"),
                DeckCard(english: "I was robbed", spanish: "me robaron"),
                DeckCard(english: "I lost my passport", spanish: "perdí mi pasaporte"),
                DeckCard(english: "I need a doctor", spanish: "necesito un médico"),
                DeckCard(english: "I'm lost", spanish: "estoy perdido/a"),
                DeckCard(english: "where is the embassy?", spanish: "¿dónde está la embajada?"),
                DeckCard(english: "I feel very sick", spanish: "me siento muy mal"),
                DeckCard(english: "I need to go to the hospital", spanish: "necesito ir al hospital"),
                DeckCard(english: "it was an accident", spanish: "fue un accidente"),
                DeckCard(english: "I don't understand", spanish: "no entiendo"),
                DeckCard(english: "do you speak English?", spanish: "¿habla inglés?"),
                DeckCard(english: "call an ambulance", spanish: "llame a una ambulancia"),
                DeckCard(english: "I was attacked", spanish: "me atacaron"),
                DeckCard(english: "I lost my luggage", spanish: "perdí mi equipaje"),
                DeckCard(english: "I need to make a call", spanish: "necesito hacer una llamada"),
                DeckCard(english: "where is the police station?", spanish: "¿dónde está la estación de policía?"),
                DeckCard(english: "my card was blocked", spanish: "mi tarjeta fue bloqueada"),
                DeckCard(english: "I need an interpreter", spanish: "necesito un intérprete"),
                DeckCard(english: "I have an emergency", spanish: "tengo una emergencia"),
                DeckCard(english: "can you help me?", spanish: "¿puede ayudarme?"),
                DeckCard(english: "I don't have money", spanish: "no tengo dinero"),
                DeckCard(english: "I lost my phone", spanish: "perdí mi teléfono"),
                DeckCard(english: "is there WiFi here?", spanish: "¿hay wifi aquí?"),
                DeckCard(english: "I need to charge my phone", spanish: "necesito cargar mi teléfono"),
                DeckCard(english: "what is the address here?", spanish: "¿cuál es la dirección aquí?"),
                DeckCard(english: "someone is following me", spanish: "alguien me está siguiendo"),
                DeckCard(english: "I need to contact my embassy", spanish: "necesito contactar a mi embajada"),
            ]

        // MARK: - f11 Nightlife & Going Out (30 cards)
        case "f11":
            return [
                DeckCard(english: "where are we going?", spanish: "¿a dónde vamos?"),
                DeckCard(english: "what's the cover charge?", spanish: "¿cuál es el cover?"),
                DeckCard(english: "a round for everyone", spanish: "una ronda para todos"),
                DeckCard(english: "cheers!", spanish: "¡salud!"),
                DeckCard(english: "I'm in a good mood", spanish: "estoy de buen humor"),
                DeckCard(english: "what music do they play?", spanish: "¿qué música tocan?"),
                DeckCard(english: "what time does it close?", spanish: "¿a qué hora cierra?"),
                DeckCard(english: "there's a long line", spanish: "hay fila larga"),
                DeckCard(english: "the bartender", spanish: "el barman"),
                DeckCard(english: "a beer please", spanish: "una cerveza por favor"),
                DeckCard(english: "without ice", spanish: "sin hielo"),
                DeckCard(english: "what cocktails do you have?", spanish: "¿qué cocteles tienen?"),
                DeckCard(english: "mezcal (agave spirit)", spanish: "el mezcal"),
                DeckCard(english: "tequila", spanish: "el tequila"),
                DeckCard(english: "margarita", spanish: "la margarita"),
                DeckCard(english: "can you give me some water?", spanish: "¿me puedes dar agua?"),
                DeckCard(english: "I'm leaving now", spanish: "ya me voy"),
                DeckCard(english: "it was an incredible night", spanish: "fue una noche increíble"),
                DeckCard(english: "we're all together", spanish: "estamos todos juntos"),
                DeckCard(english: "can you watch my spot?", spanish: "¿me cuidas el lugar?"),
                DeckCard(english: "what did you think of it?", spanish: "¿qué te pareció?"),
                DeckCard(english: "it was so much fun", spanish: "fue divertidísimo"),
                DeckCard(english: "let the party continue!", spanish: "¡que siga la fiesta!"),
                DeckCard(english: "the after-party", spanish: "el after"),
                DeckCard(english: "it's already closed", spanish: "ya está cerrado"),
                DeckCard(english: "shall we go to the next place?", spanish: "¿vamos al siguiente?"),
                DeckCard(english: "let's meet here", spanish: "quedamos aquí"),
                DeckCard(english: "I got separated from the group", spanish: "me perdí del grupo"),
                DeckCard(english: "what time does the last metro leave?", spanish: "¿a qué hora sale el último metro?"),
                DeckCard(english: "see you tomorrow", spanish: "nos vemos mañana"),
            ]

        // MARK: - f12 Home & Daily Life (30 cards)
        case "f12":
            return [
                DeckCard(english: "the apartment", spanish: "el departamento"),
                DeckCard(english: "the landlord", spanish: "el casero/la casera"),
                DeckCard(english: "the tenant", spanish: "el inquilino"),
                DeckCard(english: "the rent", spanish: "la renta"),
                DeckCard(english: "to pay the rent", spanish: "pagar la renta"),
                DeckCard(english: "utilities", spanish: "los servicios"),
                DeckCard(english: "water", spanish: "el agua"),
                DeckCard(english: "electricity", spanish: "la luz"),
                DeckCard(english: "gas", spanish: "el gas"),
                DeckCard(english: "WiFi", spanish: "el wifi"),
                DeckCard(english: "the laundry", spanish: "la lavandería"),
                DeckCard(english: "to dry clothes", spanish: "secar la ropa"),
                DeckCard(english: "to go grocery shopping", spanish: "hacer las compras"),
                DeckCard(english: "the store", spanish: "la tienda"),
                DeckCard(english: "the pharmacy", spanish: "la farmacia"),
                DeckCard(english: "the bank", spanish: "el banco"),
                DeckCard(english: "the ATM", spanish: "el cajero automático"),
                DeckCard(english: "to withdraw money", spanish: "sacar dinero"),
                DeckCard(english: "to make a transfer", spanish: "hacer una transferencia"),
                DeckCard(english: "the supermarket", spanish: "el supermercado"),
                DeckCard(english: "the elevator", spanish: "el elevador"),
                DeckCard(english: "the stairs", spanish: "las escaleras"),
                DeckCard(english: "the rooftop", spanish: "la azotea"),
                DeckCard(english: "the neighbor", spanish: "el vecino/la vecina"),
                DeckCard(english: "the condo", spanish: "el condominio"),
                DeckCard(english: "the key", spanish: "la llave"),
                DeckCard(english: "the lease contract", spanish: "el contrato de arrendamiento"),
                DeckCard(english: "the trash", spanish: "la basura"),
                DeckCard(english: "what time is maintenance?", spanish: "¿a qué hora es el mantenimiento?"),
                DeckCard(english: "I'm missing something", spanish: "me falta algo"),
            ]


        case "f13":
            return [
                DeckCard(english: "Every cloud has a silver lining", spanish: "No hay mal que por bien no venga", notes: "Lit: \"There's no evil that doesn't come for good.\" Used to console someone after something bad happens — things happen for a reason and something good will follow."),
                DeckCard(english: "Don't look a gift horse in the mouth", spanish: "A caballo regalado no se le ve el diente", notes: "Lit: \"You don't inspect the teeth of a gifted horse.\" Say this when someone complains about something they received for free."),
                DeckCard(english: "The early bird catches the worm", spanish: "El que madruga, Dios lo ayuda", notes: "Lit: \"God helps the one who rises early.\" Encouragement to be proactive. Still said by abuelas everywhere."),
                DeckCard(english: "Better late than never", spanish: "Más vale tarde que nunca", notes: "Direct equivalent. Used exactly the same way as in English — often said sarcastically when someone shows up late."),
                DeckCard(english: "Silence is golden", spanish: "En boca cerrada no entran moscas", notes: "Lit: \"Flies don't enter a closed mouth.\" More vivid than the English version — the image sticks. Said when someone is talking too much or should keep a secret."),
                DeckCard(english: "You snooze, you lose", spanish: "Camarón que se duerme, se lo lleva la corriente", notes: "Lit: \"The shrimp that falls asleep gets swept away by the current.\" One of the most uniquely Mexican expressions. Said when someone missed an opportunity by not paying attention."),
                DeckCard(english: "Easier said than done", spanish: "Del dicho al hecho, hay mucho trecho", notes: "Lit: \"From saying to doing, there's a long stretch.\" Said when someone promises big but delivery is uncertain."),
                DeckCard(english: "A bird in the hand is worth two in the bush", spanish: "Más vale pájaro en mano que ciento volando", notes: "Lit: \"Better a bird in hand than a hundred flying.\" Take what you have now rather than risk it for something uncertain."),
                DeckCard(english: "He who laughs last, laughs best", spanish: "El que ríe último, ríe mejor", notes: "Direct equivalent. Said after proving someone wrong who doubted you."),
                DeckCard(english: "Don't put all your eggs in one basket", spanish: "No pongas todos los huevos en una canasta", notes: "Direct equivalent. Financial, romantic, professional — applies everywhere."),
                DeckCard(english: "You can't make a silk purse out of a sow's ear", spanish: "Aunque la mona se vista de seda, mona se queda", notes: "Lit: \"Even if a monkey dresses in silk, it's still a monkey.\" Blunt — used to say that you can change the exterior but not the nature of something."),
                DeckCard(english: "You are who you hang out with", spanish: "El que con lobos anda, a aullar se enseña", notes: "Lit: \"He who runs with wolves learns to howl.\" Your environment shapes you. Said as a warning about bad influences."),
                DeckCard(english: "This too shall pass", spanish: "No hay mal que dure cien años", notes: "Lit: \"There's no ill that lasts a hundred years.\" Comfort during hard times — nothing stays bad forever."),
                DeckCard(english: "When life gives you lemons", spanish: "A mal tiempo, buena cara", notes: "Lit: \"To bad weather, put on a good face.\" Keep your chin up. Said to someone going through a rough patch."),
                DeckCard(english: "All that glitters is not gold", spanish: "No todo lo que brilla es oro", notes: "Direct equivalent. Don't be fooled by appearances."),
                DeckCard(english: "Greed is its own punishment", spanish: "La avaricia rompe el saco", notes: "Lit: \"Greed breaks the bag.\" When you try to take too much, you end up with nothing."),
                DeckCard(english: "None so blind as those who won't see", spanish: "No hay peor sordo que el que no quiere oír", notes: "Lit: \"There's no worse deaf person than one who refuses to hear.\" Said about someone who ignores the truth because it's inconvenient."),
                DeckCard(english: "Many a true word is spoken in jest", spanish: "Entre broma y broma, la verdad se asoma", notes: "Lit: \"Between joke and joke, the truth peeks out.\" What people say \\\"just kidding\\\" about is often what they really mean."),
                DeckCard(english: "Don't put off till tomorrow what you can do today", spanish: "No dejes para mañana lo que puedes hacer hoy", notes: "Direct equivalent. Said with mild exasperation when someone is procrastinating."),
                DeckCard(english: "Show me your friends, I'll show you who you are", spanish: "Dime con quién andas y te diré quién eres", notes: "Lit: \"Tell me who you walk with and I'll tell you who you are.\" One of the most commonly used in Mexico."),
            ]

        case "f14":
            return [
                DeckCard(english: "To have sex", spanish: "Echar un polvo", notes: "Lit: \"To throw some dust.\" Very widely used, mildly vulgar but said casually between adults. Equivalent to \"getting laid.\""),
                DeckCard(english: "To flirt aggressively", spanish: "Tirar los perros", notes: "Lit: \"To throw the dogs at someone.\" \"Me estaba tirando los perros\" = He/she was hitting on me hard. Mexico and Central America."),
                DeckCard(english: "To get completely wasted", spanish: "Ponerse hasta las chanclas", notes: "Lit: \"To get up to your flip-flops.\" Vivid image. More colorful than just \"borracho.\""),
                DeckCard(english: "To be drunk", spanish: "Estar pedo", notes: "Lit: \"To be a fart.\" One of Mexico's most common slang terms for drunk. Also \"estar bien pedo\" = totally hammered."),
                DeckCard(english: "Foreplay / warming up", spanish: "Calentar los motores", notes: "Lit: \"To warm up the engines.\" Can be used literally (warming up before exercise) or euphemistically for physical intimacy."),
                DeckCard(english: "To hook up / make out", spanish: "Enrollarse", notes: "\"Se enrollaron en la fiesta\" = They hooked up at the party. Spain-origin but used across Latin America."),
                DeckCard(english: "Heavy making out", spanish: "Darse el lote", notes: "Lit: \"To give each other the lot.\" More intense than enrollarse. Used mostly by younger speakers."),
                DeckCard(english: "To get lucky / eat a lot", spanish: "Ponerse las botas", notes: "Lit: \"To put on your boots.\" Dual meaning — eating very well OR getting lucky sexually. Context tells you which."),
                DeckCard(english: "To be in a bad mood", spanish: "Tener mala leche", notes: "Lit: \"To have bad milk.\" Vulgar origin but said casually. \"Hoy amaneció con mala leche\" = He woke up on the wrong side of the bed."),
                DeckCard(english: "To go on a bender", spanish: "Irse de juerga", notes: "\"Se fueron de juerga toda la semana\" = They partied all week. Not just one night out."),
                DeckCard(english: "To be hungover", spanish: "Estar crudo", notes: "Lit: \"To be raw.\" One of Mexico's most useful words. \"Estoy muy crudo\" = I'm so hungover."),
                DeckCard(english: "To go all in / go hard", spanish: "Meterle caña", notes: "Lit: \"To put in the sugarcane.\" \"Hay que meterle caña al proyecto\" = We need to really push this project."),
                DeckCard(english: "To have a lot of nerve", spanish: "Tener mucha cara", notes: "Lit: \"To have a lot of face.\" \"Tiene mucha cara ese tipo\" = That guy has some nerve."),
                DeckCard(english: "To crash / go to bed", spanish: "Irse al sobre", notes: "Lit: \"To go to the envelope.\" Said when you're exhausted and heading to bed. \"Me voy al sobre\" = I'm crashing."),
                DeckCard(english: "In the middle of nowhere", spanish: "Estar en el quinto pino", notes: "Lit: \"At the fifth pine tree.\" Far away, difficult to reach. \"Su casa está en el quinto pino\" = His house is in the absolute middle of nowhere."),
                DeckCard(english: "To have a thing going on", spanish: "Tener rollo", notes: "\"Tienen rollo\" = There's something going on between them. Ambiguous, which is the point."),
                DeckCard(english: "To hit the jackpot", spanish: "Sacarse el gordo", notes: "Lit: \"To pull out the fat one.\" Could be literal (lottery) or metaphorical (meeting someone amazing)."),
                DeckCard(english: "To cross the line", spanish: "Pasarse de la raya", notes: "Lit: \"To go past the line.\" \"Se pasó de la raya\" = He went too far. Widely used, socially and physically."),
                DeckCard(english: "To lose your mind", spanish: "Írsele la olla", notes: "Lit: \"The pot walks away from you.\" \"Se le fue la olla\" = She lost her mind / went off the rails."),
                DeckCard(english: "To make a move / strike", spanish: "Dar el golpe", notes: "Lit: \"To land the hit.\" Used when someone makes a bold move romantically or professionally. \"Dale el golpe ya\" = Just make your move already."),
            ]

        case "f15":
            return [
                DeckCard(english: "Love at first sight", spanish: "Flechazo", notes: "Lit: \"Arrow hit.\" The exact moment Cupid's arrow lands. \"Fue un flechazo\" = It was instant."),
                DeckCard(english: "Soulmate / other half", spanish: "Media naranja", notes: "Lit: \"Half orange.\" The idea that you're half and your partner completes you. Widely used in everyday speech."),
                DeckCard(english: "To have chemistry", spanish: "Tener química", notes: "Direct equivalent. \"Tenemos mucha química\" = We have great chemistry."),
                DeckCard(english: "To flirt / pick someone up", spanish: "Ligar", notes: "\"Fue al bar a ligar\" = He went to the bar to pick someone up. More direct than coquetear."),
                DeckCard(english: "To flirt", spanish: "Coquetear", notes: "Lighter, more playful than ligar. Like batting your eyelashes. \"Estaba coqueteando con él\" = She was flirting with him."),
                DeckCard(english: "You have an incredible smile", spanish: "Tienes una sonrisa increíble", notes: "A compliment safe to use with anyone, any gender. Reliable opener that doesn't feel aggressive."),
                DeckCard(english: "Can I have your number?", spanish: "¿Me das tu número?", notes: "The standard ask. Direct, no games. Works every time it's going to work."),
                DeckCard(english: "To be dating someone", spanish: "Salir con alguien", notes: "\"Estoy saliendo con alguien\" = I'm seeing someone. The neutral way to say you're seeing someone."),
                DeckCard(english: "I really like you", spanish: "Me encantas", notes: "Stronger than \"me gustas.\" Used when feelings are real. \"Me encantas\" lands with weight."),
                DeckCard(english: "To be in love", spanish: "Estar enamorado/a", notes: "\"Estoy enamorado\" (m) / \"Estoy enamorada\" (f). Gender-inflected. Both mean the same thing — I'm in love."),
                DeckCard(english: "To be going out with someone", spanish: "Andar con alguien", notes: "MX-specific. \"Ando con ella\" = I'm going out with her. Casual relationship status."),
                DeckCard(english: "To have a date", spanish: "Tener una cita", notes: "\"Tengo una cita esta noche\" = I have a date tonight."),
                DeckCard(english: "To make up after a fight", spanish: "Hacer las paces", notes: "Lit: \"To make the peaces.\" The reconciliation moment after an argument. \"Ya hicimos las paces\" = We made up."),
                DeckCard(english: "Long distance relationship", spanish: "Relación a distancia", notes: "Direct equivalent. Comes with the same eye rolls in any language."),
                DeckCard(english: "To be exclusive", spanish: "Ser exclusivos", notes: "\"¿Somos exclusivos?\" = Are we exclusive? The \"what are we?\" conversation outcome."),
                DeckCard(english: "To reject / ghost someone", spanish: "Dar calabazas", notes: "Lit: \"To give them pumpkins.\" The calabaza is historically a symbol of rejection in Spanish. \"Me dio calabazas\" = She rejected me."),
                DeckCard(english: "To be crazy about someone", spanish: "Estar colado/a", notes: "\"Estoy colado por ella\" (m) / \"Estoy colada por él\" (f). Lit: \"to be filtered through\" — implies you can't think straight."),
                DeckCard(english: "To confess your feelings", spanish: "Declararse", notes: "\"Se declaró\" = He/she made their feelings known. A bigger deal than just flirting."),
                DeckCard(english: "Courtship", spanish: "Cortejo", notes: "The old-school pursuit. Still used, often with gentle irony. \"Está en modo cortejo\" = He's in full courtship mode."),
                DeckCard(english: "To have butterflies", spanish: "Tener mariposas", notes: "\"Cuando lo veo tengo mariposas\" = When I see him I get butterflies. Direct equivalent, same usage."),
            ]

        default:
            return []
        }
    }
    // swiftlint:enable function_body_length
}
