//
//  TransferPatterns.swift
//  TranslateHelper
//
//  Top 20 transfer errors English speakers make when learning each language.
//  These are injected into coaching prompts to help the AI identify and
//  empathetically explain mistakes that stem from English brain patterns.
//
//  Usage: TransferPatterns.patterns(for: "pt") returns the prompt block.

import Foundation

enum TransferPatterns {

    /// Returns the transfer pattern prompt block for a given target language code.
    /// Returns empty string if language isn't in the database.
    static func patterns(for languageCode: String) -> String {
        guard let patterns = database[languageCode] else { return "" }
        let header = "TOP ENGLISH → \(languageName(for: languageCode).uppercased()) TRANSFER PATTERNS:"
        let numbered = patterns.enumerated().map { "\($0.offset + 1). \($0.element)" }.joined(separator: "\n")
        return """
        \(header)
        \(numbered)

        When the user makes an error matching one of these patterns, acknowledge the transfer warmly — \
        explain that their instinct makes sense in English, then show how \(languageName(for: languageCode)) does it differently. \
        This is not a mistake from ignorance — it's their English brain doing what it's trained to do. \
        Help them see that untraining this pattern is a normal, necessary part of the journey.
        """
    }

    private static func languageName(for code: String) -> String {
        let map: [String: String] = [
            "es": "Spanish", "pt": "Portuguese", "fr": "French", "de": "German",
            "it": "Italian", "ja": "Japanese", "ko": "Korean", "zh": "Chinese",
            "ar": "Arabic", "ru": "Russian", "nl": "Dutch", "pl": "Polish",
            "tr": "Turkish", "sv": "Swedish", "da": "Danish", "no": "Norwegian",
            "fi": "Finnish", "el": "Greek", "cs": "Czech", "ro": "Romanian",
            "hu": "Hungarian", "uk": "Ukrainian", "hi": "Hindi", "bn": "Bengali",
            "ur": "Urdu", "sw": "Swahili", "th": "Thai", "vi": "Vietnamese",
            "id": "Indonesian", "ms": "Malay", "he": "Hebrew", "fa": "Persian",
            "tl": "Filipino", "af": "Afrikaans", "ta": "Tamil", "ca": "Catalan",
            "hr": "Croatian", "sk": "Slovak", "bg": "Bulgarian",
        ]
        return map[code] ?? code.uppercased()
    }

    // MARK: - Transfer Pattern Database

    private static let database: [String: [String]] = [

        // ═══════════════════════════════════════════════════════════
        // PORTUGUESE
        // ═══════════════════════════════════════════════════════════
        "pt": [
            "Possessive word order: English says 'John's house' (possessor first) → Portuguese says 'a casa do John' (possessed first)",
            "Age expression: English 'I am 25' uses 'to be' → Portuguese 'eu tenho 25 anos' uses 'to have' (ter)",
            "Ser vs estar: English has one 'to be' → Portuguese distinguishes permanent (ser) from temporary (estar)",
            "Gender agreement: English has no grammatical gender → Portuguese nouns are masculine/feminine, adjectives must match",
            "Present continuous: English 'I am eating' → Portuguese 'estou comendo/a comer' (estar + gerund, not ser)",
            "Preposition 'a' vs 'em': English 'going to' → Portuguese 'ir a' for direction, 'estar em' for location",
            "False friend 'pretender': English 'pretend' ≠ Portuguese 'pretender' (which means 'to intend')",
            "False friend 'puxar': English speakers avoid this word → it means 'to pull,' not what it looks like",
            "Article usage: English often drops articles → Portuguese almost always requires them ('o Brasil,' 'a Maria')",
            "Personal infinitive: English has nothing like this → Portuguese can conjugate infinitives ('para eu fazer')",
            "Reflexive verbs: English 'I wake up' → Portuguese 'eu me acordo' (reflexive pronoun required)",
            "Contractions: English doesn't contract prepositions + articles → Portuguese: de + o = do, em + a = na",
            "Subjunctive mood: English rarely uses it → Portuguese requires it after doubt, desire, emotion (que eu faça)",
            "Position of adjectives: English puts adjectives before nouns → Portuguese usually puts them after (carro vermelho, not vermelho carro)",
            "Negative double: English 'I don't want anything' → Portuguese 'não quero nada' (double negative is correct)",
            "False friend 'assistir': English 'assist' = help → Portuguese 'assistir' = to watch/attend",
            "Fazer for weather/time: English 'it is hot' → Portuguese 'faz calor' (literally 'it makes heat')",
            "Ficar for becoming: English 'become' = one word → Portuguese uses 'ficar' + adjective (fiquei feliz)",
            "Tudo vs todo: English 'everything' vs 'every' → Portuguese 'tudo' (thing) vs 'todo/a' (adjective)",
            "Saudade: No English equivalent — the longing for something/someone absent. English speakers try 'I miss' but it doesn't capture the depth",
        ],

        // ═══════════════════════════════════════════════════════════
        // SPANISH
        // ═══════════════════════════════════════════════════════════
        "es": [
            "Ser vs estar: English has one 'to be' → Spanish distinguishes permanent (ser) from temporary/location (estar)",
            "Gender agreement: English has no grammatical gender → Spanish nouns are masc/fem, adjectives must agree",
            "Por vs para: English uses 'for' for both → Spanish distinguishes reason/exchange (por) from purpose/destination (para)",
            "Subjunctive mood: English rarely uses it → Spanish requires it after doubt, desire, emotion, uncertainty",
            "Gustar construction: English 'I like pizza' (subject likes) → Spanish 'me gusta la pizza' (pizza pleases me)",
            "Reflexive verbs: English 'I shower' → Spanish 'me ducho' (reflexive pronoun required)",
            "Position of adjectives: English before noun → Spanish usually after (coche rojo, not rojo coche)",
            "Negative double: English 'I don't want anything' → Spanish 'no quiero nada' (double negative correct)",
            "False friend 'embarazada': English 'embarrassed' ≠ Spanish 'embarazada' (which means 'pregnant')",
            "False friend 'realizar': English 'realize' = understand → Spanish 'realizar' = to accomplish/carry out",
            "Preposition after verbs: English 'to dream about' → Spanish 'soñar con' (different prepositions)",
            "Personal 'a': English has no equivalent → Spanish requires 'a' before human direct objects (veo a María)",
            "Present tense for ongoing: English 'I have been living here for 2 years' → Spanish present 'vivo aquí hace 2 años'",
            "Possessive word order: English 'María's house' → Spanish 'la casa de María'",
            "Hacer for weather/time: English 'it is cold' → Spanish 'hace frío' (literally 'it makes cold')",
            "Tú vs usted: English has one 'you' → Spanish formal/informal distinction changes verb conjugation",
            "Preterite vs imperfect: English past tense is one form → Spanish distinguishes completed (preterite) from ongoing (imperfect)",
            "Lo + adjective: English 'the good thing' → Spanish 'lo bueno' (neuter article, no English equivalent)",
            "Quedar vs quedarse: English 'to stay' = one verb → Spanish: quedar = to remain/meet up, quedarse = to stay in place",
            "False friend 'actualmente': English 'actually' ≠ Spanish 'actualmente' (which means 'currently')",
        ],

        // ═══════════════════════════════════════════════════════════
        // FRENCH
        // ═══════════════════════════════════════════════════════════
        "fr": [
            "Gender agreement: English has no grammatical gender → French nouns are masc/fem, all adjectives/articles must match",
            "Être vs avoir for past tense: English always uses 'have' → French uses être with movement/reflexive verbs (je suis allé)",
            "Negation sandwich: English 'not' in one place → French wraps verb with ne...pas",
            "Tu vs vous: English has one 'you' → French formal/informal affects conjugation and social perception",
            "Position of adjectives: most adjectives after the noun in French (une voiture rouge), opposite of English",
            "Passé composé vs imparfait: English past tense is one form → French distinguishes completed from ongoing",
            "False friend 'attendre': English 'attend' = go to → French 'attendre' = to wait",
            "False friend 'blessé': English 'blessed' ≠ French 'blessé' (which means 'injured')",
            "Subjunctive: English barely uses it → French requires it after 'il faut que,' 'je veux que,' etc.",
            "Preposition + infinitive: English 'before eating' → French 'avant de manger' (preposition + de + infinitive)",
            "Y and en pronouns: English has no equivalent → French replaces locations (y) and quantities (en)",
            "Article with abstract nouns: English 'love is beautiful' → French 'l'amour est beau' (article required)",
            "Reflexive verbs: English 'I wake up' → French 'je me réveille' (reflexive pronoun required)",
            "Depuis + present tense: English 'I have been living here for 2 years' → French present 'j'habite ici depuis 2 ans'",
            "C'est vs il est: English 'it is' = one form → French distinguishes general (c'est) from specific description (il est)",
            "Inversion for questions: English uses 'do' → French inverts subject-verb (parlez-vous) or uses est-ce que",
            "On = we: English 'we' → French often uses 'on' instead of 'nous' in casual speech",
            "Manquer: English 'I miss you' (subject misses) → French 'tu me manques' (you are missing to me — reversed)",
            "Partitive articles: English 'I want water' → French 'je veux de l'eau' (partitive required)",
            "Liaison and elision: English doesn't connect words phonetically → French links consonants to vowels across words",
        ],

        // ═══════════════════════════════════════════════════════════
        // GERMAN
        // ═══════════════════════════════════════════════════════════
        "de": [
            "Word order — verb at end in subordinate clauses: English keeps verb position → German sends conjugated verb to the end after 'dass,' 'weil,' etc.",
            "Three genders: English has no grammatical gender → German has masculine, feminine, AND neuter (der, die, das)",
            "Case system: English barely uses cases → German has nominative, accusative, dative, genitive — changes articles and adjective endings",
            "Separable verbs: English verbs stay together → German splits them (ich rufe dich an = I call you up)",
            "Compound nouns: English uses multiple words → German creates single compound words (Handschuh = hand + shoe = glove)",
            "Modal verb + infinitive at end: English 'I must go' → German 'ich muss gehen' (infinitive goes to end)",
            "False friend 'Gift': English 'gift' = present → German 'Gift' = poison",
            "False friend 'bekommen': English 'become' ≠ German 'bekommen' (which means 'to receive')",
            "Adjective endings: English adjectives don't change → German adjective endings depend on gender, case, and article type",
            "Perfect tense with sein: English always uses 'have' → German uses 'sein' (to be) with movement verbs (ich bin gegangen)",
            "Du vs Sie: English has one 'you' → German formal/informal is crucial socially",
            "Reflexive verbs: English 'I imagine' → German 'ich stelle mir vor' (reflexive + separable)",
            "Prepositions govern case: English prepositions don't change anything → German prepositions force accusative, dative, or both",
            "Time-manner-place order: English 'I drive to work every day' → German puts time first (ich fahre jeden Tag zur Arbeit)",
            "Doch: No English equivalent — contradicts a negative statement ('You don't like it.' 'Doch!' = 'Yes I do!')",
            "Subjunctive II for politeness: English 'I would like' → German 'ich hätte gern' / 'ich möchte' (Konjunktiv II)",
            "Nicht placement: English puts 'not' after auxiliary → German 'nicht' placement follows complex rules based on what's negated",
            "Noun capitalization: English only capitalizes proper nouns → German capitalizes ALL nouns",
            "Es gibt: English 'there is/are' → German 'es gibt' + accusative (literally 'it gives')",
            "Verbs with fixed prepositions: English 'think about' → German 'denken an' + accusative (different preposition, governed case)",
        ],

        // ═══════════════════════════════════════════════════════════
        // ITALIAN
        // ═══════════════════════════════════════════════════════════
        "it": [
            "Gender agreement: English has no grammatical gender → Italian nouns are masc/fem, articles and adjectives must match",
            "Double consonants: English doesn't distinguish → Italian 'pena' (pity) vs 'penna' (pen) — different meaning",
            "Passato prossimo vs imperfetto: English past is one form → Italian distinguishes completed from habitual/ongoing",
            "Essere vs avere in past tense: English always 'have' → Italian uses essere with movement/reflexive verbs (sono andato)",
            "Subjunctive: English barely uses it → Italian requires it after 'penso che,' 'voglio che,' etc.",
            "Ci and ne pronouns: English has no equivalent → Italian replaces locations (ci) and quantities (ne)",
            "Preposition + article contractions: English doesn't do this → Italian: di + il = del, a + la = alla",
            "False friend 'camera': English 'camera' = photo device → Italian 'camera' = room",
            "Reflexive verbs: English 'I dress' → Italian 'mi vesto' (reflexive pronoun required)",
            "Position of adjectives: English before noun → Italian usually after (macchina rossa)",
            "Piacere construction: English 'I like pizza' → Italian 'mi piace la pizza' (pizza pleases me — reversed)",
            "Stare + gerund for present continuous: English 'I am eating' → Italian 'sto mangiando' (stare, not essere)",
            "Negative double: English 'I don't see anyone' → Italian 'non vedo nessuno' (double negative correct)",
            "Tu vs Lei: English has one 'you' → Italian formal uses third person (Lei viene = 'You are coming' formally)",
            "Fare for weather: English 'it is cold' → Italian 'fa freddo' (literally 'it makes cold')",
            "Possessives with family: English 'my mother' → Italian 'mia madre' (no article with singular family + possessive)",
            "Congiuntivo in relative clauses: English 'the best restaurant I know' → Italian may require subjunctive",
            "Andare + infinitive for future: English 'I am going to eat' → Italian 'vado a mangiare' (but future tense preferred)",
            "Magari: No single English equivalent — expresses 'I wish / if only / maybe' depending on context",
            "Pronoun placement: English puts pronouns after verb → Italian attaches them to infinitives/imperatives (dimmi = tell me)",
        ],

        // ═══════════════════════════════════════════════════════════
        // JAPANESE
        // ═══════════════════════════════════════════════════════════
        "ja": [
            "Word order SOV: English is Subject-Verb-Object → Japanese is Subject-Object-Verb (I pizza eat)",
            "Particles: English uses word order for meaning → Japanese uses particles (は, が, を, に, で) to mark grammatical function",
            "Topic marker は vs subject marker が: English doesn't distinguish → Japanese marks topic (what we're talking about) differently from subject",
            "Three writing systems: English has one alphabet → Japanese uses hiragana, katakana, AND kanji together",
            "Verb at the end: English puts verb in the middle → Japanese always puts verb at the end of the sentence",
            "Formality levels: English has slight register changes → Japanese has entirely different verb forms (casual/polite/humble/honorific)",
            "Dropping subjects: English requires subjects → Japanese routinely drops them when context is clear",
            "Counting systems: English uses one number system → Japanese has different counters for flat things, long things, people, animals, etc.",
            "No plural marking: English adds -s → Japanese nouns don't change for plural (hon = book or books)",
            "Te-form connections: English uses 'and' → Japanese connects clauses with te-form of verbs",
            "Relative clauses before noun: English 'the man who is tall' → Japanese puts the whole clause before the noun",
            "No articles: English has a/the → Japanese has no articles at all",
            "Passive for suffering: English passive is neutral → Japanese passive can imply inconvenience/suffering (ame ni furareta = 'I was rained on' = the rain was a nuisance)",
            "Giving/receiving verbs: English has give/receive → Japanese has separate verbs depending on social direction (ageru, morau, kureru)",
            "い-adjectives conjugate: English adjectives don't change form → Japanese い-adjectives conjugate like verbs (atsui → atsukatta)",
            "Sentence-ending particles: English uses tone → Japanese adds ね, よ, か, な to convey nuance/emotion/questions",
            "Time expressions first: English 'I went to Tokyo yesterday' → Japanese puts time before everything else",
            "Indirect communication: English is relatively direct → Japanese often implies rather than states, especially negative things",
            "Onomatopoeia everywhere: English uses some → Japanese has thousands of sound/feeling words (ドキドキ = heart pounding, ピカピカ = sparkling)",
            "すみません versatility: English 'excuse me/sorry/thank you' = separate → Japanese すみません covers all three",
        ],

        // ═══════════════════════════════════════════════════════════
        // KOREAN
        // ═══════════════════════════════════════════════════════════
        "ko": [
            "Word order SOV: English SVO → Korean Subject-Object-Verb (I pizza eat)",
            "Particles: English uses word order → Korean uses particles (은/는, 이/가, 을/를) for grammatical function",
            "Honorific system: English has slight register → Korean has entire verb conjugation systems based on social hierarchy",
            "Verb at end: English verb in middle → Korean always ends with verb",
            "Topic vs subject: English doesn't distinguish → Korean marks topic (은/는) differently from subject (이/가)",
            "Dropping subjects: English requires them → Korean drops subjects when context is clear",
            "Counting systems: English one system → Korean has native Korean AND Sino-Korean number systems used in different contexts",
            "No articles: English has a/the → Korean has none",
            "Connector endings: English uses 'and/but/because' → Korean attaches connective endings to verbs (-고, -지만, -서)",
            "Relative clauses before noun: English 'the person who came' → Korean puts clause before noun",
            "Politeness in every sentence: English can be neutral → Korean every sentence end reveals your relationship to the listener",
            "Subject-object marking: English relies on word order → Korean particles mark what's doing and receiving the action",
            "Sino-Korean vs native vocabulary: English has one word → Korean often has two (native + Chinese-origin) with different usage contexts",
            "Passive/causative suffixes: English uses separate words → Korean adds suffixes to verb stems",
            "Vowel harmony: English doesn't have this → Korean pairs certain vowels in conjugation (양성/음성)",
            "Address terms: English uses 'you' → Korean avoids 'you' (너) in most situations, uses titles/names instead",
            "Sentence-ending particles: English uses tone → Korean 요, 습니다, etc. change formality",
            "Time before place: English flexible → Korean generally puts time expressions before place",
            "No future tense: English has 'will' → Korean uses present tense or -겠- for future contexts",
            "겸 culture: English 'humility' is optional → Korean language builds modesty into verb choices and self-reference",
        ],

        // ═══════════════════════════════════════════════════════════
        // CHINESE (Mandarin)
        // ═══════════════════════════════════════════════════════════
        "zh": [
            "Tones: English uses tone for emotion → Chinese uses 4 tones to change word meaning (mā/má/mǎ/mà = mother/hemp/horse/scold)",
            "No conjugation: English verbs change form → Chinese verbs never change (我吃, 他吃, 昨天吃 — same verb)",
            "Measure words: English 'a book' → Chinese requires a classifier 一本书 (yì běn shū — one [flat-thing] book)",
            "Topic-comment structure: English SVO → Chinese often puts topic first, comments on it",
            "了 (le) for aspect: English uses tense → Chinese uses 了 for completed action or change of state, not tense",
            "No plurals: English adds -s → Chinese nouns don't change (一个人, 三个人 — person stays same)",
            "No articles: English has a/the → Chinese has none",
            "Time before verb: English 'I went yesterday' → Chinese 'I yesterday went' (昨天我去了)",
            "把 construction: English 'I put the book on the table' → Chinese uses 把 to move object before verb for emphasis",
            "Characters not phonetic: English letters represent sounds → Chinese characters represent meaning (must learn pronunciation separately)",
            "Relative clauses before noun: English 'the book that I read' → Chinese puts the whole clause before 的 + noun",
            "是...的 for emphasis: English uses stress → Chinese uses 是...的 structure to emphasize when/where/how something happened",
            "Direction complements: English 'come in/go out' → Chinese attaches direction to verbs (进来, 出去)",
            "Resultative complements: English 'I cleaned it' → Chinese specifies result (洗干净了 = washed-clean-了)",
            "Numbers in dates: English 'March 21' → Chinese year-month-day order (2026年3月21日)",
            "没有 vs 不: English has one 'not' → Chinese: 不 for present/habitual, 没有 for past/completion",
            "Chinese names: family name first → English speakers instinctively put given name first",
            "给 versatility: English 'give/for/to' = separate → Chinese 给 covers multiple English prepositions",
            "Reduplication: English doesn't do this → Chinese repeats verbs for 'a little bit' (看看 = take a look, 试试 = give it a try)",
            "Address hierarchy: English uses 'you' freely → Chinese uses titles, family terms, and avoids direct 'you' with elders",
        ],

        // ═══════════════════════════════════════════════════════════
        // ARABIC
        // ═══════════════════════════════════════════════════════════
        "ar": [
            "Right-to-left: English reads left to right → Arabic reads right to left (including numbers in text)",
            "Root system: English words are independent → Arabic words derive from 3-letter roots (k-t-b → kitāb/kātib/maktūb = book/writer/written)",
            "No 'to be' in present: English 'he is tall' → Arabic 'huwa ṭawīl' (he tall — no verb needed)",
            "Gender in verbs: English verbs don't show gender → Arabic verbs change based on subject gender (kataba/katabat)",
            "Dual number: English has singular/plural → Arabic has singular/dual/plural",
            "Definite article al-: English 'the' is simple → Arabic ال assimilates with certain consonants (sun letters)",
            "Case endings: English lost most cases → Arabic nouns change endings for nominative/accusative/genitive",
            "Verb-Subject-Object order: English SVO → Arabic typically VSO (wrote-the boy-the letter)",
            "Broken plurals: English adds -s → Arabic plurals often change the internal pattern of the word entirely",
            "No capital letters: English capitalizes names/sentences → Arabic script has no uppercase/lowercase",
            "Emphatic consonants: English has no equivalent → Arabic distinguishes regular from emphatic versions of s, d, t, z",
            "Connected script: English letters are separate → Arabic letters connect and change shape based on position in word",
            "Idafa construction: English 'the teacher's book' → Arabic puts possessed before possessor without 'of' (kitāb al-mudarris)",
            "No indefinite article: English 'a book' → Arabic uses tanwin (nunation) ending instead of a word",
            "Hamza: English has no equivalent → Arabic has a letter for the glottal stop that follows complex placement rules",
            "Passive voice internal: English uses 'was + participle' → Arabic changes internal vowels (kataba → kutiba = was written)",
            "Formal vs dialectal: English is one language → Arabic has formal (MSA) and completely different spoken dialects per region",
            "Pronoun suffixes: English uses separate pronouns → Arabic attaches pronouns to verbs/nouns/prepositions (kitābī = my book)",
            "Verbal patterns: English uses prefixes/auxiliaries → Arabic has 10 verb patterns (forms) that modify root meaning systematically",
            "Politeness formulas: English varies → Arabic has extensive fixed phrases for every social situation (الحمد لله, إن شاء الله, etc.)",
        ],

        // ═══════════════════════════════════════════════════════════
        // RUSSIAN
        // ═══════════════════════════════════════════════════════════
        "ru": [
            "Case system: English barely uses cases → Russian has 6 cases that change noun/adjective endings",
            "No articles: English has a/the → Russian has none — context determines definiteness",
            "Aspect pairs: English has one verb → Russian has imperfective/perfective pairs for every verb (делать/сделать)",
            "Verb of motion pairs: English 'go' = one verb → Russian distinguishes walking/driving, one-way/round-trip, habitual/specific",
            "Flexible word order: English SVO is fixed → Russian word order shifts for emphasis (what's new goes last)",
            "No 'to be' in present: English 'I am a teacher' → Russian 'Я учитель' (no verb)",
            "Gender in past tense: English 'I went' → Russian changes past verb ending by gender (я ходил/ходила)",
            "Patronymic names: English uses first/last → Russian adds father's name (Иван Петрович) and it's socially important",
            "Consonant palatalization: English doesn't distinguish → Russian hard/soft consonant pairs change meaning",
            "Prefix-based verb meaning: English uses phrasal verbs → Russian changes verb meaning with prefixes (ходить → выходить/входить/уходить)",
            "Reflexive -ся verbs: English uses separate words → Russian attaches -ся to make verbs reflexive/passive",
            "Instrumental case for tools/identity: English 'with a pen' / 'as a teacher' → Russian uses instrumental case for both",
            "Genitive for negation: English 'I don't have a car' → Russian requires genitive (У меня нет машины)",
            "Numbers govern case: English 'five books' → Russian changes case after numbers (1 книга, 2 книги, 5 книг)",
            "Subjectless sentences: English requires 'it' → Russian allows subjectless (Холодно = '[It is] cold')",
            "Ты vs вы: English one 'you' → Russian formal/informal distinction is socially crucial",
            "Diminutives everywhere: English uses few → Russian adds diminutive suffixes constantly for warmth/affection (дом → домик)",
            "No continuous tense: English 'I am reading' → Russian uses imperfective without separate continuous form",
            "Dative for feelings: English 'I am cold' → Russian 'Мне холодно' (to-me [it is] cold — dative)",
            "Stress changes meaning: English stress rarely changes meaning → Russian stressed syllable can change word meaning entirely",
        ],

        // ═══════════════════════════════════════════════════════════
        // DUTCH
        // ═══════════════════════════════════════════════════════════
        "nl": [
            "Word order V2: English SVO consistently → Dutch puts verb second in main clauses but last in subordinate clauses",
            "De vs het: English 'the' is simple → Dutch has two articles with no clear rules for which nouns take which",
            "Separable verbs: English verbs stay together → Dutch splits them (ik bel je op = I call you up)",
            "Er: English has no equivalent → Dutch 'er' serves as there/it/of-it depending on context",
            "Diminutives change gender: English doesn't do this → Dutch diminutives (-je) always become het-words",
            "False friend 'slim': English 'slim' = thin → Dutch 'slim' = smart",
            "Modal + infinitive at end: English 'I must go home' → Dutch sends infinitive to end (ik moet naar huis gaan)",
            "Compound words: English uses spaces → Dutch merges words (ziekenhuis = sick + house = hospital)",
            "Double negation wrong: English 'I don't have anything' → Dutch 'ik heb niets' (single negation only)",
            "Present perfect for past: English uses simple past often → Dutch prefers present perfect in conversation (ik heb gegeten, not ik at)",
            "Adjective ending -e: English adjectives don't change → Dutch adds -e depending on article and gender (een groot huis, de grote man)",
            "Reflexive verbs: English 'I remember' → Dutch 'ik herinner me' (reflexive pronoun required)",
            "Position of 'niet': English 'not' after auxiliary → Dutch 'niet' placement follows complex rules",
            "Er + preposition: English 'about it' → Dutch 'erover' (er fuses with preposition)",
            "Om...te construction: English 'in order to' → Dutch 'om...te' with infinitive at end",
            "Plural -en vs -s: English mostly -s → Dutch uses both -en and -s with different rules",
            "Je/jij vs u: English one 'you' → Dutch informal/formal distinction",
            "Inversion after adverbs: English 'Yesterday I went' → Dutch inverts 'Gisteren ging ik' (adverb-verb-subject)",
            "Past participle ge-: English 'done/gone' → Dutch adds ge- prefix (gedaan, gegaan) but not with inseparable prefixes",
            "Continuous with 'zitten/staan/liggen te': English 'I am reading' → Dutch specifies posture while doing it (ik zit te lezen = I sit reading)",
        ],

        // ═══════════════════════════════════════════════════════════
        // ═══════════════════════════════════════════════════════════
        // POLISH
        // ═══════════════════════════════════════════════════════════
        "pl": [
            "7 cases: English barely uses cases → Polish has 7 that change every noun, adjective, and pronoun",
            "No articles: English has a/the → Polish has none",
            "Aspect pairs: every verb has imperfective/perfective forms → English has one verb",
            "Gender in past tense: verbs change by gender of subject (robiłem/robiłam)",
            "Consonant clusters: English avoids them → Polish has 'szcz,' 'prz,' 'chrz' combinations",
            "Flexible word order: emphasis changes with position → English is fixed SVO",
            "Diminutives everywhere: adds warmth/affection to almost any noun (-ek, -ka, -ko suffixes)",
            "Pan/Pani formality: English 'you' → Polish uses Mr./Mrs. + third person verb for politeness",
            "Reflexive się: many verbs require reflexive particle → English uses separate words",
            "Numbers change case: different cases required after 1, 2-4, and 5+ → English doesn't change",
            "No continuous tense: 'I am reading' → expressed through imperfective aspect, not a separate form",
            "Genitive for negation: negative sentences change noun to genitive case",
            "Instrumental for identity: 'I am a teacher' → 'Jestem nauczycielem' (teacher in instrumental)",
            "Motion verbs: distinguish one-way from round-trip travel (iść vs chodzić)",
            "Nasal vowels: ą and ę have no English equivalent — must be learned by ear",
            "Prepositions govern specific cases: each preposition requires its noun in a particular case (w + locative, do + genitive)",
            "Conditional by- particle: attaches to verb → English uses separate word 'would'",
            "Adjective agreement: adjective must match noun in gender, number, AND case → English adjectives never change",
            "Verbs of position: sitting/standing/lying are different verbs depending on orientation of object → English uses 'is'",
            "Word-building with prefixes: one root becomes dozens of verbs (pisać → napisać/opisać/wypisać/podpisać)",
        ],

        // ═══════════════════════════════════════════════════════════
        // TURKISH
        // ═══════════════════════════════════════════════════════════
        "tr": [
            "Agglutination: English uses separate words → Turkish adds suffixes one after another (evlerinizden = from your houses)",
            "Vowel harmony: suffixes change vowels to match the root → English doesn't do this",
            "SOV word order: verb always at end → English SVO",
            "No gender: Turkish has no he/she/it distinction → English speakers add unnecessary gender",
            "No articles (sort of): bir = 'a/one' but no 'the' equivalent",
            "Suffix-based grammar: prepositions become suffixes (in the house = evde, from the house = evden)",
            "Question particle mı/mi: English uses word order → Turkish adds mı/mi particle",
            "Reported speech suffix -mış: English 'apparently' → Turkish has a verb suffix for hearsay/inference",
            "Buffer consonants: y, n, s inserted between suffixes to avoid vowel collision",
            "Possessive suffixes: English 'my/your/his' → Turkish adds suffix to noun (evim = my house)",
            "Present continuous -yor: English 'I am doing' → Turkish uses -yor suffix attached to verb stem",
            "Conditional -se/-sa: English 'if' → Turkish suffix on verb",
            "Passive with -il: English uses 'was/were + past participle' → Turkish adds suffix to verb",
            "Relative clauses before noun with -en/-an: opposite of English clause order",
            "Olmak versatility: English uses be/become/happen separately → Turkish 'olmak' covers all three",
            "Consonant mutation: final consonants change when suffix starts with vowel (kitap → kitabı) → English doesn't do this",
            "Var/yok for existence: English 'there is/isn't' → Turkish uses var (exists) / yok (doesn't exist)",
            "No 'to have' verb: English 'I have' → Turkish uses possessive suffix + var (benim arabam var = my car exists)",
            "Causative suffix -tir: English uses 'make someone do' → Turkish adds suffix (yaptırmak = to make someone do)",
            "Sen vs siz: English one 'you' → Turkish informal/formal distinction socially important",
        ],

        // ═══════════════════════════════════════════════════════════
        // SWEDISH
        // ═══════════════════════════════════════════════════════════
        "sv": [
            "En vs ett: English 'a/the' → Swedish has two genders with different articles (en stol, ett bord)",
            "Definite suffix: English uses 'the' before noun → Swedish adds suffix (stolen = the chair, bordet = the table)",
            "V2 word order: verb must be second element → English is more flexible",
            "No continuous tense: 'I am eating' → Swedish uses simple present (jag äter)",
            "Å/ä/ö vowels: English has no equivalent sounds — must be learned by ear",
            "Compound words: English uses spaces → Swedish merges (sjukhus = sick house = hospital)",
            "False friend 'gift': English gift = present → Swedish 'gift' = married OR poison",
            "Reflexive sin/sitt/sina: English 'his/her' doesn't distinguish → Swedish reflexive possessive refers back to subject",
            "Passive with -s: English uses 'is/was' → Swedish adds -s to verb (huset byggs = the house is being built)",
            "Du-reformen: Swedish abandoned formal 'Ni' → everyone uses 'du' (unlike most European languages)",
            "Preposition stranding: English 'who are you talking to?' → Swedish also strands prepositions (similar comfort)",
            "Sentence adverb after verb: English 'I don't always eat' → Swedish 'jag äter inte alltid' (adverb after verb in main clause)",
            "Supine vs past participle: English has one form → Swedish distinguishes (har ätit vs äten)",
            "Lagom: no English equivalent — means 'just the right amount' — culturally significant concept",
            "Pronunciation doesn't match spelling: English speakers read Swedish phonetically and get it wrong",
            "Inversion after adverbs: English 'Yesterday I went' → Swedish inverts 'Igår gick jag' (adverb-verb-subject)",
            "Double definite: with adjective → article AND suffix needed (den stora bilen = the big car-the)",
            "Att + infinitive vs att + clause: 'to do' vs 'that' — same word, different function → English uses different words",
            "Sj-sound: unique Swedish sound (sjö, skjorta) → no English equivalent, varies by dialect",
            "Deponent verbs: passive form but active meaning (hoppas = to hope) → English has nothing like this",
        ],

        // ═══════════════════════════════════════════════════════════
        // DANISH
        // ═══════════════════════════════════════════════════════════
        "da": [
            "En vs et: two genders with different articles → English has one 'a/the'",
            "Definite suffix: 'the' attaches to end of noun (huset = the house) → English puts 'the' before",
            "Glottal stop (stød): unique to Danish → English has no equivalent, changes word meaning",
            "V2 word order: verb second → English more flexible",
            "No continuous: 'I am eating' = 'jeg spiser' → simple present covers it",
            "Compound words without spaces → English separates them",
            "Numbers are vigesimal: 50 = halvtreds (half-third-times-twenty) → English uses base-10",
            "False friend 'rolig': English 'roly' ≠ Danish 'rolig' (which means 'calm')",
            "Reflexive sin/sit/sine possessives: distinguishes 'his own' from 'his (someone else's)' → English doesn't",
            "Passive with -s or blive: two passive constructions → English has one",
            "Pronunciation extremely reduced compared to spelling → reading aloud will sound wrong",
            "Soft 'd': English 'd' → Danish 'd' between vowels sounds like English 'th' or 'l'",
            "Sentence adverbs after verb in main clause, before verb in subordinate → English doesn't split this way",
            "Hygge: no English equivalent — cozy contentment — culturally essential concept",
            "Double definite: adjective + definite article + noun with suffix (den store hund = the big dog-the)",
            "Modal + infinitive at end in subordinate clauses: 'I know that he must go' → verb order flips in Danish",
            "At vs og: 'to' (before infinitive) vs 'and' → English speakers confuse when to use which",
            "Inversion after adverbs: front an adverb and subject-verb swap → English doesn't require this",
            "R-sound varies by dialect: uvular R in Copenhagen, trilled R elsewhere → English has one R",
            "Implicit subject 'man': English 'one/you/people' → Danish uses 'man' as generic subject (man kan ikke = one cannot)",
        ],

        // ═══════════════════════════════════════════════════════════
        // NORWEGIAN
        // ═══════════════════════════════════════════════════════════
        "no": [
            "Bokmål vs Nynorsk: two written standards → English has one — learners must choose",
            "Three genders: masculine, feminine, neuter → English has none",
            "Definite suffix: huset = the house → English puts 'the' before noun",
            "V2 word order: verb second in main clauses → English more flexible",
            "No continuous: 'I am eating' = 'jeg spiser' → simple present covers it",
            "Compound words without spaces → English separates them",
            "Tonal accent: two tones distinguish word meaning → English doesn't use tone for meaning",
            "Reflexive sin/si/sitt possessives: distinguish 'his own' from 'his (someone else's)' → English doesn't",
            "Passive with -s or bli: two constructions → English has one",
            "False friend 'rar': English 'rare' ≠ Norwegian 'rar' (which means 'nice/sweet')",
            "Sentence adverb placement differs between main and subordinate clauses → English doesn't split",
            "Modal + infinitive: infinitive goes to end in subordinate clauses → English keeps it after modal",
            "Kos/koselig: similar to Danish hygge — warmth and coziness with no direct English translation",
            "Preposition stranding accepted (like English) — easier transition here",
            "Past participle agreement with subject in some dialects → English participles don't agree",
            "Inversion after adverbs: 'I går gikk jeg' (Yesterday went I) → English doesn't invert",
            "Double definite: adjective requires both article AND suffix (det store huset = the big house-the)",
            "Å vs og: 'to' (before infinitive) vs 'and' → English speakers mix these up",
            "Dialect-heavy: spoken Norwegian varies enormously by region → no single 'correct' pronunciation",
            "Nå/da particles: add nuance to sentences → no English equivalents",
        ],

        // ═══════════════════════════════════════════════════════════
        // FINNISH
        // ═══════════════════════════════════════════════════════════
        "fi": [
            "15 cases: English barely uses cases → Finnish has 15 that change every noun",
            "Agglutination: suffixes stack (talossanikin = in my house too) → English uses separate words",
            "No grammatical gender: ei hän = he/she → English speakers add unnecessary gender distinctions",
            "No articles: English a/the → Finnish has none",
            "Vowel harmony: front/back vowels don't mix in words → English doesn't have this",
            "Consonant gradation: consonants change between strong/weak forms → English has nothing similar",
            "No prepositions — postpositions: English 'in the house' → Finnish 'talon sisällä' (house-of inside)",
            "Verb negation: negative verb conjugates, main verb doesn't → English negates with 'don't/doesn't'",
            "Partitive case: English 'some water' → Finnish uses partitive case ending (vettä)",
            "No future tense: present tense + context → English has 'will'",
            "Long vowels and consonants change meaning: tuli (fire) vs tuuli (wind) vs tulli (customs)",
            "Word order relatively free but default SVO — topic-focus affects placement",
            "Possessive suffixes: kirjani = my book → English uses separate word 'my'",
            "Sisu: no English equivalent — inner determination/resilience — culturally defining concept",
            "Questions with -ko/-kö suffix: English 'Do you?' → Finnish adds suffix to verb (tiedätkö = do you know)",
            "Object case depends on completion: partitive for incomplete action, accusative for complete → English doesn't mark this",
            "Third infinitive: English 'to eat' → Finnish has multiple infinitive forms for different grammatical functions",
            "Passive as impersonal: 'syödään' = 'one eats / let's eat' → English needs separate constructions",
            "Spoken Finnish very different from written: puhekieli drops endings and shortens words → learners face two languages",
            "No equivalent of 'please': politeness through conditional mood and tone, not a magic word",
        ],

        // ═══════════════════════════════════════════════════════════
        // GREEK
        // ═══════════════════════════════════════════════════════════
        "el": [
            "Different alphabet: English uses Latin → Greek uses its own alphabet (some letters look similar but sound different)",
            "Three genders: masculine, feminine, neuter → English has none",
            "Case system: nominative, accusative, genitive → changes articles and noun endings",
            "Verb-first common: English SVO → Greek often puts verb first for emphasis",
            "Continuous vs simple aspect: Greek distinguishes these more rigorously than English",
            "Subjunctive with να: Greek uses subjunctive much more than English → required after many common verbs",
            "No infinitive: English 'to go' → Greek uses να + conjugated verb (να πάω)",
            "Definite article before names: English 'Maria' → Greek 'η Μαρία' (the Maria)",
            "Double consonant letters: ντ = 'd', μπ = 'b', γκ = 'g' → English speakers read them as two sounds",
            "Formal εσείς vs informal εσύ: English one 'you' → Greek formal/informal affects verb conjugation",
            "Clitic pronouns before verb: English 'I see him' → Greek 'τον βλέπω' (him I-see)",
            "Stress mark changes meaning: English stress is flexible → Greek requires correct stress (written with accent mark)",
            "Passive voice very common: Greek uses passive for many situations where English uses active",
            "Augment in past tense: past tense adds ε- prefix to verb → English just changes the verb",
            "Diminutives and augmentatives: suffixes change noun meaning and emotional tone → English rarely does this",
            "Clitic doubling: pronoun appears twice (τον βλέπω τον Γιάννη) → English uses pronoun once",
            "Perfective vs imperfective stems: different verb stems for completed vs ongoing → English uses one stem",
            "Negation δεν/μην: different negative words for indicative vs subjunctive → English uses one 'not'",
            "Genitive for possession: English 'John's book' → Greek uses genitive case (το βιβλίο του Γιάννη)",
            "Cultural exclamations: ρε, μωρέ, παιδί μου — discourse particles with no English translation",
        ],

        // ═══════════════════════════════════════════════════════════
        // CZECH
        // ═══════════════════════════════════════════════════════════
        "cs": [
            "7 cases: English barely uses cases → Czech has 7 that change nouns, adjectives, pronouns",
            "No articles: English a/the → Czech has none — context determines definiteness",
            "Flexible word order: changes emphasis → English is fixed SVO",
            "Aspect pairs: imperfective/perfective for every verb → English has one form",
            "Consonant clusters: 'strč prst skrz krk' (stick finger through throat) — no vowels needed",
            "Háčky and čárky: ě, š, č, ř, ž — sounds English doesn't have, especially ř (unique to Czech)",
            "Gender in past tense: verb endings show subject's gender → English verbs don't change",
            "Reflexive se/si: many verbs require reflexive particle → English uses separate words",
            "Motion verb pairs: going on foot vs by vehicle → English uses one 'go'",
            "Conditional by- particle: attaches to auxiliary → English uses separate word 'would'",
            "Diminutives very common: adds warmth/affection to almost any noun",
            "Vykání (vy) vs tykání (ty): formal/informal 'you' with strict social rules",
            "Numbers govern case: different cases after different numbers (1 kniha, 2 knihy, 5 knih)",
            "No continuous tense: aspect handles the distinction → English 'I am doing' vs 'I do'",
            "Prepositions govern specific cases: each preposition forces its noun into a particular case",
            "Instrumental for means/tools: 'with a pen' = 'perem' (pen in instrumental) → English uses 'with'",
            "Verbal prefixes change meaning: jít → přijít/odejít/vejít (come/leave/enter) → systematic prefix system",
            "Genitive for negation: negative sentences require genitive case on object",
            "Vocative for addressing: Czech has a special case for calling someone → English just uses the name",
            "Být (to be) in past tense uses gender: byl/byla/bylo → English 'was' doesn't change",
        ],

        // ═══════════════════════════════════════════════════════════
        // ROMANIAN
        // ═══════════════════════════════════════════════════════════
        "ro": [
            "Definite article suffix: English 'the house' → Romanian 'casa' (article attached to end)",
            "Three genders: masculine, feminine, neuter → neuter acts as masc in singular, fem in plural",
            "Case system: nominative-accusative, genitive-dative → changes article endings",
            "Subjunctive with să: Romanian uses subjunctive much more than English → required after many verbs",
            "No infinitive in common use: English 'I want to go' → Romanian 'vreau să merg' (want that I-go)",
            "Reflexive verbs: se + verb for many actions English doesn't make reflexive",
            "Preposition + article contractions → English keeps them separate",
            "False friend 'a realiza': English 'realize' (understand) ≠ Romanian (to achieve/accomplish)",
            "Clitic pronouns: pronoun placement before/after verb follows complex rules",
            "Vocative case: Romanian has a special form for addressing people → English doesn't",
            "Conditional with ar: different auxiliary system than English 'would'",
            "Latin vocabulary + Slavic grammar = unique combination that surprises learners",
            "Double negation: 'nu am nimic' = I don't have nothing → correct in Romanian",
            "Articulated possessives: al/a/ai/ale before possessive → no English equivalent",
            "Diacritics matter: ă, â, î, ș, ț change pronunciation significantly",
            "Clitic doubling: pronoun appears both as clitic and full form → English uses pronoun once",
            "Adjective usually after noun: 'mașină roșie' (car red) → English puts adjective before",
            "Pe for human direct objects: 'îl văd pe Ion' (I see PE Ion) → like Spanish 'personal a'",
            "Hai/haide imperative: informal invitation particle → no English equivalent",
            "Romanian is the closest living language to Latin — but English speakers who know Spanish/French get tripped up by false similarities",
        ],

        "hu": [
            "Agglutination extreme: suffixes stack endlessly → English uses separate words",
            "18 cases: English barely uses cases → Hungarian has 18",
            "Vowel harmony: suffixes change based on front/back vowels in root → English has nothing similar",
            "No grammatical gender: ő = he/she/it → English speakers add unnecessary distinctions",
            "Definite vs indefinite conjugation: verb changes based on whether object is definite → unique to Hungarian",
            "SOV word order: default, but very flexible for emphasis",
            "No 'to have': English 'I have' → Hungarian 'nekem van' (to-me there-is)",
            "Postpositions instead of prepositions: 'the house behind' not 'behind the house'",
            "Possessive suffixes: házam = my house → English uses separate word",
            "Focus position before verb: whatever comes right before verb is emphasized → English uses stress",
            "No future tense: present + context → English uses 'will'",
            "Conditional -na/-ne suffix: English 'would' → Hungarian adds suffix",
            "Prefixed verbs separate: like German, verb prefixes detach in certain constructions",
            "Double letters: ss, ll, tt all represent long consonants → changes meaning",
            "Numbers before noun stays singular: 'three house' not 'three houses' (három ház)",
        ],

        "uk": [
            "Cyrillic alphabet: different letters, some look like Latin but sound different",
            "7 cases: noun/adjective endings change for each grammatical function",
            "Aspect pairs: imperfective/perfective for every verb",
            "No articles: English a/the → Ukrainian has none",
            "Flexible word order for emphasis",
            "Gender in past tense: verb shows subject's gender",
            "Reflexive -ся verbs: suffix makes verbs reflexive/passive",
            "Ти vs Ви: informal/formal 'you' — social rules apply",
            "No 'to be' in present tense: 'I student' not 'I am a student'",
            "Motion verb pairs: walking vs riding distinguished",
            "Genitive for negation: negative changes noun case",
            "Soft sign ь: changes consonant pronunciation → no English equivalent",
            "Prefixes change verb meaning: ходити → виходити/входити/заходити",
            "Dative for feelings: 'мені холодно' = to-me cold",
            "Ukrainian-specific vocabulary differs from Russian despite similarities",
        ],

        "hi": [
            "SOV word order: verb at end → English SVO",
            "Postpositions: 'house in' not 'in house' (ghar mein)",
            "Gender in verbs: verb agrees with subject's gender → English verbs don't",
            "Split ergativity: past tense of transitive verbs agrees with object, not subject → very confusing for English speakers",
            "No articles: English a/the → Hindi has none (but 'ek' = one serves as indefinite)",
            "Compound verbs: two verbs together modify meaning → English uses adverbs",
            "Honorific system: tum/tū/āp = three levels of 'you' → English has one",
            "Retroflex consonants: ट, ड, ण — tongue curls back → English doesn't have these",
            "Aspirated consonants: क vs ख — breathed vs unbreathed → English doesn't distinguish",
            "Oblique case before postpositions: nouns change form before postpositions",
            "No 'have': 'I have a book' → 'mere pās kitāb hai' (my near book is)",
            "Devanagari script: each character = consonant + inherent vowel",
            "Light verb constructions: 'work do' instead of 'work' as verb",
            "Conjunct verbs: noun + karnā/honā pattern for thousands of actions",
            "Code-switching with English: Hinglish is extremely common — learners must navigate mixed speech",
        ],

        "bn": [
            "SOV word order: verb at end",
            "Postpositions instead of prepositions",
            "No grammatical gender in modern Bengali (unlike Hindi)",
            "Verb changes for formality: tui/tumi/āpni = three 'you' levels",
            "Classifiers required with numbers: like Chinese/Japanese measure words",
            "Bengali script: complex, with conjunct consonants",
            "No articles but -ṭa/-ṭi suffixes serve similar function",
            "Retroflex consonants: tongue position sounds English doesn't have",
            "Compound verbs: two verbs together for nuance",
            "Honorific verb conjugation changes entire verb form",
            "No 'have' verb: possession expressed differently",
            "Vowel nasalization changes meaning",
            "Relative clauses with je...se construction: different structure than English",
            "Echo words: repetition with vowel change for emphasis (chā-ṭā = tea and such)",
            "Cultural formality embedded in pronoun choice affects every sentence",
        ],

        "ur": [
            "SOV word order: verb always at end",
            "Nastaliq script: right-to-left, connected, with dots distinguishing letters",
            "Gender in everything: nouns, adjectives, verbs all agree in gender",
            "Postpositions: follow the noun instead of preceding it",
            "Honorific āp/tum/tū: three levels of 'you' with social significance",
            "No articles: definiteness from context",
            "Compound verbs: light verb constructions pervasive",
            "Aspirated consonants: breathing distinction English doesn't make",
            "Retroflex consonants: tongue curled back",
            "Split ergativity: past tense agreement shifts to object",
            "Izāfat construction: Persian-influenced possessive linking",
            "Arabic/Persian vocabulary layer: formal Urdu draws heavily from Arabic/Persian",
            "Respect vocabulary: different words entirely for eat/sleep/come based on who you're addressing",
            "Right-to-left reading: opposite of English",
            "Poetic/literary register very different from spoken — learners must navigate both",
        ],

        "sw": [
            "Noun class system: 18 classes with prefixes → English has no equivalent (m-/wa-, ki-/vi-, etc.)",
            "Agglutination: prefixes and suffixes on verbs (ninakupenda = I-you-love)",
            "SVO word order: similar to English — easier transition",
            "No grammatical gender: noun classes are based on meaning categories, not gender",
            "Tense markers as prefixes: na- (present), li- (past), ta- (future) attach to verb",
            "Subject prefix required on verb: verb already shows who's acting",
            "Object prefix on verb: 'I see you' = 'ninakuona' (ni-na-ku-ona = I-present-you-see)",
            "Adjective agreement with noun class: adjective takes prefix matching noun class",
            "No articles: noun class prefix implies definiteness",
            "Bantu vs Arabic vocabulary layers: coastal Swahili has heavy Arabic influence",
            "Relative clause markers: -ye-/-o- infixed in verb",
            "Copula ni/si: 'is/is not' — different from English 'to be' which conjugates",
            "Habitual vs progressive tense: hu- (always do) vs na- (doing now) → English doesn't distinguish as clearly",
            "Associative na: 'of/with/and' all covered by one word",
            "Politeness through vocabulary choice rather than verb conjugation",
        ],

        "th": [
            "Tones: 5 tones change word meaning → English uses tone for emotion only",
            "No conjugation: verbs never change form → English changes tense/person",
            "No plurals: context determines quantity → English adds -s",
            "Classifiers required: like Chinese/Japanese measure words with numbers",
            "No spaces between words: Thai script runs continuously → English has clear word boundaries",
            "Krub/ka particles: gender-based politeness particles end every polite sentence",
            "Pronouns change by social status: dozens of 'I' and 'you' options based on relationship",
            "SVO but flexible: similar to English base order but topic-comment structure common",
            "Aspirated vs unaspirated: English doesn't distinguish p/pʰ, t/tʰ, k/kʰ → Thai does",
            "No past/future tense markers required: context + time words → English requires tense marking",
            "Reduplication for emphasis/plural: สวย (beautiful) → สวยๆ (beautifully/various beautiful things)",
            "Vowel length changes meaning: short vs long vowels → English doesn't consistently distinguish",
            "Consonant clusters simplified: English 'strong' → Thai would reduce initial cluster",
            "Royal/religious vocabulary: entirely different words for actions when referring to monks or royalty",
            "Mai (ไม่) negation: simply place before verb → simpler than English but tone must be correct",
        ],

        "vi": [
            "Tones: 6 tones change word meaning → English uses tone for emotion",
            "No conjugation: verbs never change → English changes for tense/person",
            "No plurals: context or classifiers indicate quantity",
            "Classifiers required with numbers and demonstratives",
            "SVO word order: same as English — easier transition",
            "Adjectives after nouns: 'house big' not 'big house'",
            "No articles but demonstratives/classifiers serve similar function",
            "Kinship pronouns: 'I' and 'you' change based on age/relationship (anh/chị/em/con/bác)",
            "No tense marking on verbs: đã (past), đang (present), sẽ (future) are optional separate words",
            "Sentence-final particles: à, nhé, nhỉ add nuance/politeness → English uses tone",
            "No 'to be' before adjectives: 'tôi vui' = I happy (no 'am')",
            "Reduplication: changes meaning (đỏ = red, đo đỏ = reddish)",
            "Topic-comment structure common: topic first, comment after",
            "Passive rarely used: Vietnamese prefers active constructions → English uses passive freely",
            "Regional dialects: Northern/Central/Southern sound very different → English speakers learn one and struggle with others",
        ],

        "id": [
            "No conjugation: verbs never change → English changes for tense/person/number",
            "No tenses: time words + context → English requires tense marking",
            "No grammatical gender",
            "SVO word order: same as English — easy transition",
            "Affixation system: prefixes/suffixes change word function (me-, ber-, -kan, -an) → English uses separate words",
            "Reduplication for plurals: buku-buku = books → English adds -s",
            "No articles: English a/the → Indonesian has none",
            "Formal/informal registers: different vocabulary for each",
            "Measure words with numbers: similar to Chinese classifiers",
            "Yang for relative clauses: 'yang' = who/which/that → simpler than English relative pronouns",
            "Active me- prefix: meN- prefix changes based on first consonant of root → complex rules",
            "Passive di- prefix: 'the book was read' → 'buku itu dibaca'",
            "Base words vs derived words: same root becomes noun/verb/adjective with different affixes",
            "Ber- prefix for intransitive: berjalan = to walk → English doesn't mark transitivity this way",
            "Sudah/belum for completion: 'already' and 'not yet' more important than past tense → English doesn't think this way",
        ],

        "ms": [
            "Very similar to Indonesian with regional differences",
            "No conjugation or tenses: time words + context",
            "No grammatical gender",
            "SVO word order like English",
            "Affixation system: me-, ber-, -kan, -an change word function",
            "Reduplication for plurals",
            "No articles",
            "Malay vs formal registers differ significantly",
            "Classifier system with numbers",
            "Yang for relative clauses",
            "Lah/kah particles: emphasis and question particles → no English equivalent",
            "Active/passive voice through prefix: meN- (active) vs di- (passive)",
            "Sudah/belum completion markers more important than tense",
            "Jawi script: Arabic-based alternative writing system still used in some contexts",
            "Code-mixing with English (Manglish) very common — learners must navigate mixed speech",
        ],

        "he": [
            "Right-to-left: reading direction opposite of English",
            "Root system: 3-letter roots generate word families (like Arabic) — k-t-v → katav/miktav/ktovet",
            "No vowels written (usually): vowel marks optional in modern Hebrew → English always writes vowels",
            "Gender in verbs: verb changes based on subject gender and number → English verbs don't",
            "Gender in numbers: 'three' changes form based on noun gender → English numbers don't change",
            "No 'to be' in present: 'ani student' not 'ani hu student' (for present tense)",
            "Construct state (smikhut): 'house of the teacher' → special noun form → English uses 'of'",
            "Verb patterns (binyanim): 7 patterns modify root meaning → English uses prefixes/auxiliaries",
            "Dual number for time/body parts: special form for pairs (yomayim = two days)",
            "Definite article ה prefix: attaches to noun → English 'the' is separate word",
            "Preposition + pronoun fusion: 'to me' = לי (single word) → English keeps them separate",
            "SVO but VSO possible: word order more flexible than English",
            "No indefinite article: English 'a' → Hebrew just uses no article",
            "Guttural consonants: ח, ע → sounds English doesn't have",
            "Modern Hebrew revival: some constructions feel artificial to native speakers → learners get conflicting feedback",
        ],

        "fa": [
            "SOV word order: verb at end → English SVO",
            "Right-to-left: Arabic script (modified) → opposite reading direction",
            "No grammatical gender: او = he/she → English speakers add unnecessary distinctions",
            "Ezafe construction: -e suffix links nouns → 'house of Ali' = 'khāne-ye Ali'",
            "No articles (sort of): -i = indefinite marker suffix, no definite article",
            "Compound verbs everywhere: noun + kardan/shodan → English uses single verbs",
            "Formal/informal pronouns: to/shomā → English one 'you'",
            "Arabic loan words: formal Persian draws heavily from Arabic vocabulary",
            "Verb always at end of clause → English puts it in middle",
            "Continuous with dāshtan: 'dāram miravam' = I have I-go = I am going → unique construction",
            "Subjunctive very common: after 'that,' desire, doubt → used much more than English",
            "Colloquial vs formal: spoken Persian drops many features of written → learners face two languages",
            "Taarof: elaborate politeness system → English politeness is comparatively simple",
            "Numbers before noun: same as English, but different digit shapes in formal text",
            "Relative clause with ke: 'ke' = who/which/that → simpler than English but clause structure differs",
        ],

        "tl": [
            "VSO word order: verb first → English SVO",
            "Focus system: verb changes to show focus on actor/object/location/etc. → nothing like this in English",
            "Ang/ng/sa markers: mark grammatical roles → English uses word order",
            "No conjugation for person: verb doesn't change for I/you/he → English does",
            "Aspect (not tense): completed/ongoing/contemplated → English uses past/present/future",
            "Linker na/-ng: connects modifier to noun → English just places them adjacent",
            "Po/opo particles: politeness markers → English has no equivalent",
            "Reduplication: changes meaning (araw = day, araw-araw = every day)",
            "Borrowed Spanish/English words: integrated with Filipino grammar → can confuse English speakers",
            "Pronoun system: inclusive vs exclusive 'we' (tayo vs kami) → English has one 'we'",
            "Question words in situ: question word can stay in place → English moves it to front",
            "Existential may: 'there is' = 'may' → different from English structure",
            "Tag questions with di ba: 'right?' = 'di ba' → simpler than English tag formation",
            "Code-switching with English (Taglish) very common",
            "Respect vocabulary: different words for 'eat/come/go' based on respect level",
        ],

        "af": [
            "Double negation: nie...nie required → English 'not' once",
            "No conjugation: one verb form for all persons → English changes for he/she/it",
            "V2 word order: verb second in main clauses, like Dutch/German",
            "Separable verbs: prefix detaches (ek bel hom op = I call him up)",
            "No grammatical gender: die = the (for all nouns) → simpler than Dutch/German",
            "Past tense with het + ge-: het geëet = have eaten → English uses 'ate' or 'have eaten'",
            "Compound words without spaces: siektehuis = sick house = hospital",
            "Is for 'to be' in all persons: ek is, jy is, hy is → English changes (I am, you are, he is)",
            "Modal + infinitive at end: ek moet gaan = I must go",
            "Diminutive -tjie/-jie: very common, adds warmth → English rarely uses diminutives",
            "Reflexive with -self: hom self = himself → but used more broadly than English",
            "Passive with word: 'die huis word gebou' = the house is being built → uses 'word' not 'is'",
            "Position of nie: second nie at end of clause → English doesn't double negate",
            "False friend similarities with Dutch: many words look the same but meaning shifted",
            "Relatively easy for English speakers: simplified grammar compared to Dutch/German",
        ],

        "ta": [
            "SOV word order: verb at end",
            "Agglutination: suffixes stack on words → English uses separate words",
            "No prepositions — case suffixes and postpositions: 'in house' = 'vīṭṭil' (house-in)",
            "Two 'we' forms: inclusive (nāmma) vs exclusive (nāṅkaḷ) → English has one",
            "No articles: English a/the → Tamil has none",
            "Formal/informal pronouns: nīṅkaḷ/nī → English one 'you'",
            "Retroflex consonants: ட, ண, ற → tongue positions English doesn't use",
            "No gender in plural: gender only in singular third person",
            "Verb conjugation shows person/number/gender: one verb form carries all this information",
            "Relative participles instead of relative clauses: adjective-like forms before nouns",
            "Negative verbs: separate negative conjugation → English uses 'not/don't'",
            "Tamil script: each consonant has inherent 'a' vowel",
            "Formal literary Tamil vs spoken Tamil: very different → learners face two varieties",
            "Classifiers used with numbers",
            "Respect vocabulary: verb choice changes based on social relationship",
        ],

        "ca": [
            "Very similar to Spanish but with key differences that trip up learners of both",
            "Weak pronouns: complex clitic pronoun system (en, hi, ho) → no English equivalent",
            "Definite articles: el/la/els/les but also personal article 'en/na' before names",
            "Ser vs estar: like Spanish but some different usage rules",
            "Gender agreement: like Spanish/French",
            "Subjunctive: used more than English, similar to Spanish",
            "Periphrastic past: anar + infinitive for past → unique construction",
            "Reflexive verbs: similar to Spanish/French",
            "Pronouns before infinitive: different placement rules from Spanish",
            "Ç and l·l: sounds and spellings English doesn't have",
            "Cultural and political dimension: language choice carries identity significance",
            "False friends with Spanish: some words look same but mean different things",
            "Neuter pronoun ho: 'it' for abstract concepts → English uses 'it' for everything",
            "Definite article before possessives: 'la meva casa' (the my house) → English doesn't do this",
            "Catalan has more vowel sounds than Spanish — English speakers who learned Spanish get confused",
        ],

        "hr": [
            "7 cases: English barely uses cases → Croatian changes nouns, adjectives, pronouns",
            "No articles: English a/the → Croatian has none",
            "Aspect pairs: imperfective/perfective for every verb",
            "Three genders: masculine, feminine, neuter with complex agreement",
            "Flexible word order for emphasis",
            "Reflexive se: many verbs require reflexive particle",
            "Definite vs indefinite adjective forms: two forms of every adjective → English has one",
            "Motion verb pairs: distinguish direction from location",
            "Ti vs Vi: informal/formal 'you'",
            "Cyrillic option: Croatian uses Latin script but learners encounter Cyrillic in the region",
            "Accent system: pitch accent on different syllables → English uses stress differently",
            "Collective numbers: special forms for groups → English doesn't have these",
            "Verbal nouns: gerund-like forms with different grammar than English -ing",
            "Clitic ordering: strict rules for pronoun clitic sequence → English has freer pronoun placement",
            "Regional vocabulary: coast vs interior use different words for same concepts",
        ],

        "sk": [
            "7 cases: extensive case system changes nouns, adjectives, pronouns",
            "No articles: English a/the → Slovak has none",
            "Aspect pairs: imperfective/perfective for every verb",
            "Ľ, ŕ, ĺ: Slovak has syllabic consonants → entire syllables without vowels",
            "Flexible word order for emphasis",
            "Gender in past tense: verb shows subject's gender",
            "Reflexive sa/si: many verbs require reflexive",
            "Diminutives very common and culturally important",
            "Ty vs vy: informal/formal 'you'",
            "Motion verbs: directional pairs like other Slavic languages",
            "Numbers govern case: different cases after different number ranges",
            "Rhythmic law: long syllable can't follow long syllable → affects suffixes",
            "Ň, ť, ď: palatalized consonants → English doesn't have these",
            "No continuous tense: aspect handles the distinction",
            "Conditional with by particle: different mechanism than English 'would'",
        ],

        "bg": [
            "No case system: Bulgarian is the exception among Slavic languages — cases mostly disappeared",
            "Definite article suffix: -ът/-ят/-та/-то → attaches to end of noun (like Romanian, unlike English 'the')",
            "No infinitive: English 'to go' → Bulgarian uses да + conjugated verb (да отида)",
            "Verb aspect: imperfective/perfective pairs → English has one form",
            "Cyrillic alphabet: different letters than English Latin alphabet",
            "Clitic doubling: pronouns appear twice (на мен ми = to me to-me) → English uses pronoun once",
            "Renarrated mood: special verb form for reporting what someone else said → English uses 'reportedly/apparently'",
            "No gender in plural: gender only matters in singular",
            "Three genders in singular: masculine, feminine, neuter",
            "Evidentiality: verb form shows whether you witnessed something or heard about it → English doesn't mark this",
            "Subject pronouns optional: verb conjugation shows person → English requires subject",
            "Questioning with ли: particle ли turns statement into question → English changes word order",
            "Reflexive се/си: many verbs require reflexive",
            "Numbers + plural: special counting form for masculine nouns after numbers → unique feature",
            "Ти vs Вие: informal/formal 'you'",
        ],
    ]
}
